=== yoanaB/ASP/XML_Files/XML_Files/cat_breeds.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fif ( cat_breeds, categories, groups ) >
    <!ELEMENT cat_breeds (cat_breed+)>
        <!ELEMENT cat_breed (name,country,head,ears,eyes,tail, year_of_establishment, colors,fur,image,size,personality)>
             <!ATTLIST cat_breed standart_number ID #REQUIRED>
             <!ATTLIST cat_breed group IDREFS #REQUIRED>
             <!ATTLIST cat_breed category CDATA #IMPLIED>
         <!ELEMENT name (#PCDATA)>
         <!ELEMENT country (country_name,country_continent,country_government_type)>
         <!ATTLIST country capital  CDATA #REQUIRED>
         <!ATTLIST country official_language CDATA #IMPLIED>
         <!ATTLIST country  time_zone  CDATA  #IMPLIED>
         <!ATTLIST country currency  CDATA #IMPLIED>
         <!ATTLIST country country_code CDATA #IMPLIED>
             <!ELEMENT country_name (#PCDATA)>
             <!ELEMENT country_continent (#PCDATA)>
             <!ELEMENT country_government_type (#PCDATA)>
         
         <!ELEMENT head (#PCDATA)>
         <!ELEMENT ears (#PCDATA)>
         <!ELEMENT eyes (#PCDATA)>
         <!ELEMENT tail (#PCDATA)>
         <!ELEMENT year_of_establishment (#PCDATA)>
        
         <!ELEMENT colors (primary_color,secondary_color,prefered_color)>
            <!ELEMENT primary_color (#PCDATA)>
            <!ELEMENT secondary_color (#PCDATA)>
            <!ELEMENT prefered_color (#PCDATA)>
         <!ELEMENT fur (#PCDATA)>
         <!ELEMENT image (#PCDATA)>
            <!ELEMENT size (males_size,females_size)>
                <!ELEMENT males_size (#PCDATA)>
                <!ELEMENT females_size (#PCDATA)>
         <!ELEMENT personality (#PCDATA)>
         <!ELEMENT categories (category+) >
            <!ELEMENT category (#PCDATA)>
                <!ATTLIST category category_id ID #REQUIRED>
         <!ELEMENT groups (group+)>
            <!ELEMENT group (#PCDATA)>
                <!ATTLIST group group_code ID #REQUIRED >

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_5_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="MAN" group="groupC" category="cat3">
      <name>Манкс</name>
      <country capital="Токио" official_language="японски" time_zone="UTC/GMT  +9 hours" currency="японска йена" country_code="JAP">
        <country_name>Япония</country_name>
        <country_continent>Азия</country_continent>
        <country_government_type>република</country_government_type>
      </country>
      <year_of_establishment>1949</year_of_establishment>
      <head>Главата е кръгла, но е по-дълга, отколкото широка.</head>
      <ears>Широко поставените уши са със среден размер, широки в основата и постепенно изтъняващи и закръглени накрая.</ears>
      <eyes>Очите са много кръгли и широко поставени, под лек наклон към носа.</eyes>
      <tail>1.Тип rumру (код 51) - няма опашни прешлени и е налице пълна липса на опашка, като има вдлъбнатина на мястото на липсващата опашка, която се констатира с поставяне на палеца;
			2.Тип rumpy-riser (код 52) - с малко опашни прешлени, които обикновено са свързани неподвижно - представлява къс изправен израстък;
			3.Тип stumpy (код 53) - остатъчна къса опашка с деформации (удебеления);
			4.Тип longy (код 54) - опашката се доближава до нормалната дължина, но е видимо по-къса.</tail>
      <colors>
        <primary_color>сребриск</primary_color>
        <secondary_color>златист</secondary_color>
        <prefered_color>бял</prefered_color>
      </colors>
      <fur>къса</fur>
      <image>http://www.kotkite.com/img/articles/thumbs/0208070837_6_.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality></personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat3">напълно разпознати котки 3</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_18_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="RAG" group="groupB" category="cat1">
      <name>Регдол</name>
      <country capital="Вашингтон" official_language="английски" time_zone="UTC/GMT  -7 hours" currency="долар" country_code="USA">
        <country_name>САЩ</country_name>
        <country_continent>Северна Америка</country_continent>
        <country_government_type>феерална република</country_government_type>
      </country>
      <year_of_establishment>1991</year_of_establishment>
      <head>Главата е дълга, с клиновидна форма, с широк череп и ясно изразени дебели бузи.</head>
      <ears>
      </ears>
      <eyes> Очите са едри, с овална форма, сини на цвят. </eyes>
      <tail>
      </tail>
      <colors>
        <primary_color>едноцветни</primary_color>
        <secondary_color>бели лапи</secondary_color>
        <prefered_color>двуцветни</prefered_color>
      </colors>
      <fur>Космената покривка е мека и гъста, по структура напомня на заешка козина, като нейната плътност зависи от сезона.</fur>
      <image>http://www.kotkite.com/img/articles/0108070316_6_.jpg</image>
      <size>
        <males_size>10</males_size>
        <females_size>8</females_size>
      </size>
      <personality>
      </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat1">напълно разпознати котки - 1</category>
  </categories>
  <groups>
    <group group_code="groupB">екзотични котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_4_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="GRX" group="groupC" category="cat4">
      <name>Немски рекс</name>
      <country capital="Берлин" official_language="немски" time_zone="UTC/GMT  -2 hours" currency="евро" country_code="GER">
        <country_name>Германия</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type></country_government_type>
      </country>
      <year_of_establishment>1982</year_of_establishment>
      <head>кръглата широка глава.</head>
      <ears>Ушите са на голямо разстояние едно от друго, със заоблени върхове и с мека гъста козина от външната страна. </ears>
      <eyes> красивите кръгли очи, които са в тон с цвета на козината</eyes>
      <tail>Опашката е плътна, с дълги косми.</tail>
      <colors>
        <primary_color>в един тон</primary_color>
        <secondary_color>в съчетание с бяло</secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur> Козината на Немски Рекс на пипане е като кадифе. Тя е много къса и леко вълнообразна. Гъстотата й варира от тънка мека покривка до плътна равномерна структура.</fur>
      <image>http://gradcontent.com/lib/600x350/german-rex.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Опашката е плътна, с дълги косми.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки - 4</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/Cat3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
    <cat_breeds>
        <cat_breed standart_number="JBT" group="groupA" category="cat3">
            <name>Японски бобтейл</name>
            <country capital="Токио" country_code="JAP">
                <country_name>Япония</country_name>
                <country_continent>Азия</country_continent>
                <country_government_type>република</country_government_type>
            </country>
            <year_of_establishment>1960</year_of_establishment>
            <head>
                Главата с с почти правилна триъгълна форма. Има високо разположени скули, а бузите са развити и закръглени. Носът е сравнително дълъг, със сплеснат край. 
            </head>
            <ears>
                Ушите са високо и широко поставени, големи, стоящи под ъгъл към главата, което създава впечатление, че те са леко наклонени напред.            </ears>
            <eyes>
                Очите са големи, с овална форма, косо поставени. Техният цвят трябва да хармонира на окраската на козината.             </eyes>
            <tail>
                Опашката е необичайно къса и е типичен признак на породата. В спокойно състояние бобтейлът държи опашката високо повдигната, при което нейната дължина е от 6 до 9 см (при измерване в изтегнато положение нейната максимална дължина може да достигне 10-12 см).             </tail>
            
            <colors>
                <primary_color>черен</primary_color>
                <secondary_color>червен</secondary_color>
                <prefered_color>бял</prefered_color>
            </colors>
            <fur>Космената покривка на опашката е дълга и груба, с космено кичурче накрая, неприлягаща, растяща във всички направления. Козината на тялото е мека, коприноподобна, без забележимо подкосмие. Има два типа - късокосмести и полудългокосмести. </fur>
            <image></image>
            <size>
                <males_size>5</males_size>
                <females_size>4</females_size>
            </size>
            <personality>
                Котките от тази порода са дружелюбни, ласкави и лесно се привързват към членовете на семейството, но понякога могат да проявяват твърд характер.
            </personality>
        </cat_breed>
    </cat_breeds>
    <categories>
        <category category_id="cat3">Напълно разпознати породи - категория 2</category>
    </categories>
    <groups>
        <group group_code="groupA">EXO, PER, JBT</group>
    </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_17_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="PER" group="groupA" category="cat1">
      <name>Персийска котка</name>
      <country capital="Техеран" official_language="фарси" time_zone="UTC/GMT  +3 hours" currency="ирански риал" country_code="IRN">
        <country_name>Иран</country_name>
        <country_continent>Азия</country_continent>
        <country_government_type>република</country_government_type>
      </country>
      <year_of_establishment>1949</year_of_establishment>
      <head>Характерна е сплесканата муцуна с малък и широк нос, изпъкнали скули и масивна брадичка. Погледнати в профил челото и брадичката са в една вертикална линия. </head>
      <ears>Ушите са малки, със заоблени върхове, странично и ниско поставени. Челото е високо и заоблено отгоре.</ears>
      <eyes>това са котки с открит поглед при който горната линия на гъбата на носа се намира малко под долната мислена линия на очите, които трябва да са кръгли и широко отворени. </eyes>
      <tail>Къса, права без дефекти (възли) и дебела в основата си. Силно и равномерно окосмена.
</tail>
      <colors>
        <primary_color>черен</primary_color>
        <secondary_color>бял</secondary_color>
        <prefered_color>син</prefered_color>
      </colors>
      <fur>Дълга и мека, гъста и обилна, коприненоподобна, неприлепваща по тялото; чиста и разресана. Силно окосмяване на бузите, оприличаващо го на "бакенбарди" и около шията образува ефектна яка, която надолу към гърдите преминава към богато "жабо". На корема е дълга и много мека. Козината трябва да бъде чиста, искряща, стояща като леко наелектризирана. Мазната козина свидетелства за недостатъчно балансирано хранене, недостатъчна поддръжка и изложбена подготовка.</fur>
      <image>
      </image>
      <size>
        <males_size>4</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Къса, права без дефекти (възли) и дебела в основата си. Силно и равномерно окосмена.
</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat1">Напълно разпознати котки - 1</category>
  </categories>
  <groups>
    <group group_code="groupA">нови породи</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_10_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="SPH" group="groupC" category="cat4">
      <name>Сфинкс</name>
      <country capital="Кайро" official_language="арабски" time_zone="UTC/GMT  +2 hours" currency="египетска лира" country_code="EGP">
        <country_name>Египет</country_name>
        <country_continent>Африка</country_continent>
        <country_government_type>република</country_government_type>
      </country>
      <year_of_establishment>2002</year_of_establishment>
      <head></head>
      <ears>Характерни са големите уши</ears>
      <eyes> Очите са искрящо сини на цвят.</eyes>
      <tail></tail>
      <colors>
        <primary_color></primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>голо тяло</fur>
      <image>http://e4p-bg.com/wp-content/uploads/2014/09/Sphynx_1.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Ако сте решили да си вземете такава котка, не забравяйте – тя не счита себе си за котка! </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки 4</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/1_well_formed_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="BSS" group="groupB" category="cat3">
      <name>Британска късокосместа</name>
      <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
        <country_name>Великобритания</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1960</year_of_establishment>
      <head>Главата на тази котка е кръгла, масивна, с широк череп, поставена на отлично развита къса и силна шия.</head>
      <ears> Ушите й са малки и широки в основата, леко закръглени, широко поставени като подчертават закръглените контури на главата.  </ears>
      <eyes>Очите на британската късокосместа котка са големи, кръгли, широко поставени. Цветът им е в съответствие с очите.</eyes>
     
      <colors>
        <primary_color>синя</primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>Козината на британската късокосместа котка е къса, плътна, неприлепваща, с гъст подкосъм.</fur>
      <image>http://www.catbg.net/domashni/pictures/Porodi/british_short/british3.jpg</image>
      <size>
        <males_size>8</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Британките са контактни и комуникативни, дружелюбни и ласкави. </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat3">напълно разпознати котки 3</category>
  </categories>
  <groups>
    <group group_code="groupB">екзотични котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_9_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="SIA" group="groupD" category="cat4">
      <name>Сиамска котка</name>
      <country capital="Банкок" official_language="тайски" time_zone="UTC/GMT  +7 hours" currency="тайландки бат" country_code="THL">
        <country_name>Тайланд</country_name>
        <country_continent>Азия</country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1949</year_of_establishment>
      <head> Новият стандарт включвал лека костна система и клиновидна глава.</head>
      <ears>Ушите са големи и прави, разположени далече едно от друго, широки в основата си. </ears>
      <eyes>Очите са с бадемовидна форма, сапфиреносини на цвят.</eyes>
      <tail>Опашката е права, заострена накрая, без възли и дефекти по нея. </tail>
      <colors>
        <primary_color>сиамска с кафяви отмети</primary_color>
        <secondary_color>сиамска със сини отмети</secondary_color>
        <prefered_color>сиамска с лилави отмети</prefered_color>
      </colors>
      <fur>къса</fur>
      <image>http://www.kotkite.com/img/articles/thumbs/0208070837_6_.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality></personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки 4</category>
  </categories>
  <groups>
    <group group_code="groupD">редки котки</group>
  </groups>
</fif>
