=== yoanaB/ASP/XML_Files/XML_Files/cat_breeds.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fif ( cat_breeds, categories, groups ) >
    <!ELEMENT cat_breeds (cat_breed+)>
        <!ELEMENT cat_breed (name,country,head,ears,eyes,tail, year_of_establishment, colors,fur,image,size,personality)>
             <!ATTLIST cat_breed standart_number ID #REQUIRED>
             <!ATTLIST cat_breed group IDREFS #REQUIRED>
             <!ATTLIST cat_breed category CDATA #IMPLIED>
         <!ELEMENT name (#PCDATA)>
         <!ELEMENT country (country_name,country_continent,country_government_type)>
         <!ATTLIST country capital  CDATA #REQUIRED>
         <!ATTLIST country official_language CDATA #IMPLIED>
         <!ATTLIST country  time_zone  CDATA  #IMPLIED>
         <!ATTLIST country currency  CDATA #IMPLIED>
         <!ATTLIST country country_code CDATA #IMPLIED>
             <!ELEMENT country_name (#PCDATA)>
             <!ELEMENT country_continent (#PCDATA)>
             <!ELEMENT country_government_type (#PCDATA)>
         
         <!ELEMENT head (#PCDATA)>
         <!ELEMENT ears (#PCDATA)>
         <!ELEMENT eyes (#PCDATA)>
         <!ELEMENT tail (#PCDATA)>
         <!ELEMENT year_of_establishment (#PCDATA)>
        
         <!ELEMENT colors (primary_color,secondary_color,prefered_color)>
            <!ELEMENT primary_color (#PCDATA)>
            <!ELEMENT secondary_color (#PCDATA)>
            <!ELEMENT prefered_color (#PCDATA)>
         <!ELEMENT fur (#PCDATA)>
         <!ELEMENT image (#PCDATA)>
            <!ELEMENT size (males_size,females_size)>
                <!ELEMENT males_size (#PCDATA)>
                <!ELEMENT females_size (#PCDATA)>
         <!ELEMENT personality (#PCDATA)>
         <!ELEMENT categories (category+) >
            <!ELEMENT category (#PCDATA)>
                <!ATTLIST category category_id ID #REQUIRED>
         <!ELEMENT groups (group+)>
            <!ELEMENT group (#PCDATA)>
                <!ATTLIST group group_code ID #REQUIRED >

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_16_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="CRX" group="groupC" category="cat4">
      <name>Корниш рекс</name>
      <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
        <country_name>Великобритания</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1950</year_of_establishment>
      <head>
      </head>
      <ears> големи уши са разположени отгоре на сравнително малката им яйцевидна главица </ears>
      <eyes> големи изразителни очи, леко косо, широко поставени, с наситен плътен цвят в съответствие с този на козината.</eyes>
      <tail>Имат дълга, тънка, много гъвкава и подвижна опашка, която равномерно изтънява към върха си.</tail>
      <colors>
        <primary_color>охра</primary_color>
        <secondary_color>черна</secondary_color>
        <prefered_color>червена</prefered_color>
      </colors>
      <fur>Заради късата им и фина козина, която не линее, много хора считат корниш рекс за хипоалергенни котки. </fur>
      <image>http://www.catbg.net/domashni/pictures/Porodi/cornish_rex/sleeping_cornish.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Имат дълга, тънка, много гъвкава и подвижна опашка, която равномерно изтънява към върха си.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки - 4</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_8_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="PEB" group="groupD" category="cat4">
      <name>Петерболд</name>
      <country capital="Москва" official_language="руски" time_zone="UTC/GMT  -2 hours" currency="рубла" country_code="RUS">
        <country_name>Русия</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type></country_government_type>
      </country>
      <year_of_establishment>2012</year_of_establishment>
      <head>Главата има клиновидна форма. </head>
      <ears>Ушите са големи, широки в основата си и леко заострени в края си.</ears>
      <eyes> Очите са големи, с бадемовидна форма. </eyes>
      <tail></tail>
      <colors>
        <primary_color>в един тон</primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>няма козина </fur>
      <image>http://gradcontent.com/lib/600x350/german-rex.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Петерболдът е подходяща порода за семейства с по-големи деца, за сами живеещи хора с 
	  други домашни любимци, но преди всичко неговите собственици трябва да имат опит в отглеждането на котки. 
	  Той е интелигентна, приятелски настроена котка, която не таи злоба.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки - 4</category>
  </categories>
  <groups>
    <group group_code="groupD">редки котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/Cat1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/XML_Files/cat_breeds.dtd">
<fif>
    <cat_breeds>
        <cat_breed standart_number="EXO" group="groupA" category="cat1">
            <name>Екзотична котка</name>
            <country capital="Вашингтон" country_code="USA">
                <country_name>САЩ</country_name>
                <country_continent>Северна Америка</country_continent>
                <country_government_type>република</country_government_type>
            </country>
            <head>
                Главата на екзотичната котка е със среден размер и е с кръгла форма. Муцуната е леко сплескана като на персийската котка.
            </head>
            <ears>
                ушите са малки и са насочени надолу
            </ears>
            <eyes>
                Очите са големи, намират се на разстояние едно от друго и са много изразителни. Те са жълти или сини на цвят. 
            </eyes>
            <tail>Опашката на екзотичната котка не е много голяма и се стеснява към края си.</tail>
            <year_of_establishment>1966</year_of_establishment>
            <colors>
                <primary_color>кафяв</primary_color>
                <secondary_color>черен</secondary_color>
                <prefered_color>бял</prefered_color>
            </colors>
            <fur>Козината е къса и мека като кадифе, под основния слой има по-къс слой козина. </fur>
            <image></image>
            <size>
                <males_size>5</males_size>
                <females_size>4</females_size>
            </size>
            <personality>
                Екзотичната котка има доброжелателен и спокоен характер. Основното, което ги отличава от флегматичните персийски котки, е тяхната любознателност. 
            </personality>
        </cat_breed>
    </cat_breeds>
    <categories>
        <category category_id="cat1">Напълно разпознати породи - категория 1</category>
    </categories>
    <groups>
        <group group_code="groupA">EXO, PER</group>
    </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_15_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="ABY" group="groupC" category="cat4">
      <name>Абисинска котка</name>
      <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
        <country_name>Великобритания</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1949</year_of_establishment>
      <head>Главата й е средно широка, леко клиновидна на изящна дълга шия. Муцуната й не е заострена</head>
      <ears>Ушите й са широко поставени, големи в основата си; имат формата на чаша и завършват със снопчета козина на върха. </ears>
      <eyes>Очите й са с бадемовидна форма, широко поставени под съвсем малък ъгъл спрямо носа и много изразителни. Обградени са с фин тъмен контур. </eyes>
      <tail>Опашката е плътна, с дълги косми.</tail>
      <colors>
        <primary_color>охра</primary_color>
        <secondary_color>черна</secondary_color>
        <prefered_color>червена</prefered_color>
      </colors>
      <fur>Козината й е къса, тънка, блестяща (копринена) и плътно прилепнала към тялото с наситен, равномерен основен цвят и ясно изразен тикинг. </fur>
      <image>http://www.catbg.net/domashni/pictures/Porodi/aby/Abyssinian2_web.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Опашката е плътна, с дълги косми.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки - 4</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>
