=== yoanaB/ASP/XML_Files/XML_Files/cat_breeds.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fif ( cat_breeds, categories, groups ) >
    <!ELEMENT cat_breeds (cat_breed+)>
        <!ELEMENT cat_breed (name,country,head,ears,eyes,tail, year_of_establishment, colors,fur,image,size,personality)>
             <!ATTLIST cat_breed standart_number ID #REQUIRED>
             <!ATTLIST cat_breed group IDREFS #REQUIRED>
             <!ATTLIST cat_breed category CDATA #IMPLIED>
         <!ELEMENT name (#PCDATA)>
         <!ELEMENT country (country_name,country_continent,country_government_type)>
         <!ATTLIST country capital  CDATA #REQUIRED>
         <!ATTLIST country official_language CDATA #IMPLIED>
         <!ATTLIST country  time_zone  CDATA  #IMPLIED>
         <!ATTLIST country currency  CDATA #IMPLIED>
         <!ATTLIST country country_code CDATA #IMPLIED>
             <!ELEMENT country_name (#PCDATA)>
             <!ELEMENT country_continent (#PCDATA)>
             <!ELEMENT country_government_type (#PCDATA)>
         
         <!ELEMENT head (#PCDATA)>
         <!ELEMENT ears (#PCDATA)>
         <!ELEMENT eyes (#PCDATA)>
         <!ELEMENT tail (#PCDATA)>
         <!ELEMENT year_of_establishment (#PCDATA)>
        
         <!ELEMENT colors (primary_color,secondary_color,prefered_color)>
            <!ELEMENT primary_color (#PCDATA)>
            <!ELEMENT secondary_color (#PCDATA)>
            <!ELEMENT prefered_color (#PCDATA)>
         <!ELEMENT fur (#PCDATA)>
         <!ELEMENT image (#PCDATA)>
            <!ELEMENT size (males_size,females_size)>
                <!ELEMENT males_size (#PCDATA)>
                <!ELEMENT females_size (#PCDATA)>
         <!ELEMENT personality (#PCDATA)>
         <!ELEMENT categories (category+) >
            <!ELEMENT category (#PCDATA)>
                <!ATTLIST category category_id ID #REQUIRED>
         <!ELEMENT groups (group+)>
            <!ELEMENT group (#PCDATA)>
                <!ATTLIST group group_code ID #REQUIRED >

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_1_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="BEN" group="groupB" category="cat3">
      <name>Бенгалска котка</name>
      <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
        <country_name>Великобритания</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1960</year_of_establishment>
      <head> Главата на бенгалската котка е с клиновидна форма, но с овален контур. </head>
      <ears> Ушите не са особено големи и са заоблени.</ears>
      <eyes> Очите на бенгалската котка са овални или бадемовидни. Те са големи и се допускат всички цветове освен синия.</eyes>
      <tail>Опашката е дебела, не много дълга, като в края си се стеснява и има черно петно в заобления си край. </tail>
      <colors>
        <primary_color>златиста</primary_color>
        <secondary_color>кафява</secondary_color>
        <prefered_color>черна</prefered_color>
      </colors>
      <fur>Козината на бенгалската котка е гъста, много мека, като при младите животни може да е по-дълга. Основното, което отличава бенгалските котки от другите породи, са петната по козината,</fur>
      <image>http://www.catbg.net/domashni/pictures/Porodi/british_short/british3.jpg</image>
      <size>
        <males_size>7</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Бенгалската котка е изключително умно същество. </personality>
    </cat_breed>
	<cat_breed standart_number="SOM" group="groupB" category="cat1">
      <name>Сомали</name>
	  <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
	    <country_name>Великобритания</country_name>
	    <country_continent>Европа</country_continent>
	    <country_government_type>кралство</country_government_type>
	  </country>
      <year_of_establishment>1960</year_of_establishment>
      <head>с формата на обърнат триъгълник.</head>
      <ears> Ушите са едри и в тях може да има кичури козина. </ears>
      <eyes>  разположени леко скосено и са овални.</eyes>
      <tail>опашката е дълга и пухкава.</tail>
      <colors>
        <primary_color>бял с червени петна</primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>Козината му е дълга и пухкава, искрящо бяла, с кафеникави или черни петна по главата.</fur>
      <image>http://gradcontent.com/lib/500x350/turkish-van1.jpg</image>
      <size>
        <males_size>8</males_size>
        <females_size>4</females_size>
      </size>
      <personality>котка с независим характер и понякога взима самостоятелни решения.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat3">напълно разпознати котки 3</category> 
	<category category_id="cat1">напълно разпознати котки 1</category>
  </categories>
  <groups>
    <group group_code="groupB">екзотични котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_6_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="MAU" group="groupD" category="cat3">
      <name>Египетска мау</name>
      <country capital="Кайро" official_language="арабски" time_zone="UTC/GMT  +2 hours" currency="египетска лира" country_code="EGP">
        <country_name>Египет</country_name>
        <country_continent>Африка</country_continent>
        <country_government_type>република</country_government_type>
      </country>
      <year_of_establishment>1992</year_of_establishment>
      <head>Главата на египетската мау е кръгла.</head>
      <ears> Ушите са остри, разположени са на голямо разстояние едно от друго.</ears>
      <eyes> Очите на египетската мау са искрящо зелени на цвят.</eyes>
      <tail>Опашката е средна на дължина, като към края си се стеснява и е с остър край. Козината на египетската мау е къса. Тя варира в няколко цвята.</tail>
      <colors>
        <primary_color>светлосив с петна</primary_color>
        <secondary_color>сив</secondary_color>
        <prefered_color>сребрист</prefered_color>
      </colors>
      <fur>Козината на египетската мау е къса. Тя варира в няколко цвята.</fur>
      <image>http://gradcontent.com/lib/500x350/egyptian-mau3.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Египетската мау е изключително интелигентно животно, което с радост ще се включи в обучението, ако то се основава на игри и похвали, придружени с лакомство. </personality>
    </cat_breed>
	
	<cat_breed standart_number="NFO" group="groupB" category="cat2">
      <name>Нормежка горска котка</name>
      <country capital="Берлин" official_language="немски" time_zone="UTC/GMT  -2 hours" currency="евро" country_code="GER">
        <country_name>Германия</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type></country_government_type>
      </country>
      <year_of_establishment>1959</year_of_establishment>
      <head>относително голяма, широка, с трапецовидна форма.</head>
      <ears>средно големи, широки в основата, с форма на равностранен триъгълник, като в края са леко закръглени и имат снопчета от косми на върха.</ears>
      <eyes>широко поставени, средно големи, с овална или бадемовидна форма, като обагрянето им хармонира с окраската на козината.</eyes>
      <tail>средно дълга, дебела в основата, изтъняваща и затьпена в края.</tail>
      <colors>
        <primary_color>агути-фактор</primary_color>
        <secondary_color>агути фактор с бяло</secondary_color>
        <prefered_color>агути-фактор</prefered_color>
      </colors>
      <fur> Козината им не изисква старателно ресане, тъй като тя сама поддържа чистотата и порядъка й.</fur>
      <image>http://www.kotkite.com/img/articles/thumbs/3107070742_6_.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>4</females_size>
      </size>
      <personality>притежава силно изразен майчински инстинкт. </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat3">напълно разпознати котки 3</category>
    <category category_id="cat2">напълно разпознати котки 2</category>
  </categories>
  <groups>
    <group group_code="groupD">редки котки</group>
    <group group_code="groupB">екзотични котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_20_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="TUA" group="groupB" category="cat2">
      <name>Турска ангора</name>
      <country capital="Анкара" official_language="турски" time_zone="UTC/GMT  +3 hours" currency="лира" country_code="TUR">
        <country_name>Турция</country_name>
        <country_continent>Азия</country_continent>
        <country_government_type>република</country_government_type>
      </country>
      <year_of_establishment>1988</year_of_establishment>
      <head>Главата има триъгълна форма.</head>
      <ears> Ушите са широки в основата си, заострени в крайщата и гъсто окосмени. </ears>
      <eyes>Очите са с бадемовидна форма, като могат да бъдат сини, оранжеви, зелени или разноцветни. Представителите със сини очи често са глухи, а тези, които имат едно синьо око са глухи от неговата страна.</eyes>
      <tail>Опашката е плътна, с дълги косми.</tail>
      <colors>
        <primary_color>ангорка бяла със сини очи</primary_color>
        <secondary_color>ангорка бяла с различен цвят очи</secondary_color>
        <prefered_color>ангорска червена ивичеста таби с оранжеви очи</prefered_color>
      </colors>
      <fur>Коприненият тоалет на ангорската котка е много впечатляващ. По тялото козината се състои от твърде фини и доста по-дълги от останалите косми - те започват от нивата на якичката към бутовете, до под корема.</fur>
      <image>http://www.kotkite.com/img/articles/thumbs/3107070713_6_.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Опашката е плътна, с дълги косми.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat2">напълно разпознати котки - 2</category>
  </categories>
  <groups>
    <group group_code="groupB">екзотични котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/3_well_formed_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
    <cat_breeds>
        <cat_breed standart_number="DRX" group="groupC" category="cat4">
            <name>Девон рекс</name>
            <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
                <country_name>Великобритания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>кралство</country_government_type>
            </country>
            <year_of_establishment>1960</year_of_establishment>
            <head>
                Главата е с триъгълна форма, изразени скули и масивно подбрадие. Носът е къс и има ясно изразен стоп, а челото е скосено.
            </head>
            <ears>
                Ушите са големи, широки в основата и със закръглени краища, изцяло покрити с гъсти коприненоподобни косми с окосмени или без космено покритие кожни гънки в задната част на ушната раковина (т. нар. "шалче в ухото"
            </ears>
            <eyes>
                Очите са широко поставени, големи, с бадемовидна форма, леко удължени в посока към ушите. Цветът им трябва да хармонира с обагрянето на козината - жълт или зелен. 
            </eyes>
            <tail>Опашката е тънка, дълга, заострена накрая, покрита с гъсти, къси косми.</tail>
            
            <colors>
                <primary_color>кафяв</primary_color>
                <secondary_color>черен</secondary_color>
                <prefered_color>бял</prefered_color>
            </colors>
            <fur>Козината се състои от къси, нежни, меки и къдрави косми, с подкосмие. Вибрисите са силно развити, средно дълги и вълнисти. Окраската може да бъде разнообразна.</fur>
            <image></image>
            <size>
                <males_size>5</males_size>
                <females_size>4</females_size>
            </size>
            <personality>
                Котките от породата девон рекс са енергични и игриви. Обичат ласките и лесно се привързват към членовете на семейството.
            </personality>
        </cat_breed>
    </cat_breeds>
    <categories>
        <category category_id="cat4">Напълно разпознати породи - категория 1</category>
    </categories>
    <groups>
        <group group_code="groupC">ABY, CRX, DRX, DSP, GRX, JBT, RUS, SOM, SPH </group>
    </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_7_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="OSH" group="groupD" category="cat4">
      <name>Ориенталска късокосместа</name>
      <country capital="Берлин" official_language="немски" time_zone="UTC/GMT  -2 hours" currency="евро" country_code="GER">
        <country_name>Германия</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type></country_government_type>
      </country>
      <year_of_establishment>1959</year_of_establishment>
      <head>Главата е средно голяма, с клиновидна форма, дълга, с тясна муцуна и със забележимо издадена напред брадичка. </head>
      <ears>Ушите са големи, широки в основата, като краищата им са леко заострени. </ears>
      <eyes> Очите са широко поставени, средно големи, с бадемовидна форма, с яркозелен цвят (само белите са с яркосин цвят), косо по отношение на носа. </eyes>
      <tail>Опашката е дълга, права, завършваща конусовидно. Козината е къса, нежна, блестяща, плътно прилепваща към тялото. </tail>
      <colors>
        <primary_color>кафяв</primary_color>
        <secondary_color>черен</secondary_color>
        <prefered_color>синя</prefered_color>
      </colors>
      <fur>Козината е къса, нежна, блестяща, плътно прилепваща към тялото.</fur>
      <image>http://www.kotkite.com/img/articles/thumbs/0208070823_6_.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Ориенталските котки са много енергични, игриви и любопитни животни. За тяхното отглеждане е необходим просторен дом за движение и игри.</personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки - 4</category>
  </categories>
  <groups>
    <group group_code="groupD">редки котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_19_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="RUS" group="groupC" category="cat4">
      <name>Синя руска</name>
      <country capital="Москва" official_language="руски" time_zone="UTC/GMT  -2 hours" currency="" country_code="RUS">
        <country_name>Русия</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type></country_government_type>
      </country>
      <year_of_establishment>1949</year_of_establishment>
      <head>Има сравнително къса клинообразна глава, прав нос, големи заострени уши, широки в основата си, отвесно поставени. </head>
      <ears> големи уши са разположени отгоре на сравнително малката им яйцевидна главица </ears>
      <eyes> Очите са големи и изразителни, широко поставени, с бадемовидна форма и зелено обагряне. Крайниците са високи и елегантни.</eyes>
      <tail>Има овални лапи и сравнително дълга островърха опашка. </tail>
      <colors>
        <primary_color>сиво-синя</primary_color>
        <secondary_color>черна</secondary_color>
        <prefered_color>червена</prefered_color>
      </colors>
      <fur> Но най-красивата породна особеност е равномерното сиво-синьо оцветяване на козината, която е копринсномека (плюшоподобна), с къси, гъсти, нежни и меки косми с подкосмие, което има еднаква дължина с покривните косми. </fur>
      <image>http://www.kotkite.com/img/articles/thumbs/2807071245_6_.jpg</image>
      <size>
        <males_size>6</males_size>
        <females_size>5</females_size>
      </size>
      <personality>Има овални лапи и сравнително дълга островърха опашка. </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки - 4</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_3_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="EUR" group="groupC" category="cat4">
      <name>Европейска котка</name>
      <country capital="Лондон" official_language="английски" time_zone="UTC/GMT  -2 hours" currency="паунд" country_code="GBR">
        <country_name>Великобритания</country_name>
        <country_continent>Европа</country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1981</year_of_establishment>
      <head>кръгла глава </head>
      <ears>еголеми уши, много гъст подкосъм</ears>
      <eyes> Очите на европейската късокосместа са чисти, прозрачни. Цветът им може да бъде зелен, жълт, оранжев или син в зависимост от окраската на козината.</eyes>
      <tail>Опашката й е със средна дължина, желателно е да е широка в основата, постепенно изтъняваща и със завито връхче. </tail>
      <colors>
        <primary_color>златист</primary_color>
        <secondary_color>сребрист</secondary_color>
        <prefered_color>бял</prefered_color>
      </colors>
      <fur>къса</fur>
      <image>http://www.catbg.net/domashni/pictures/Porodi/eur/eur2.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Това, което ще забележите от пръв поглед, е че европейските късокосмести котки винаги са активни и жизнерадостни.</personality>
    </cat_breed>
	
	<cat_breed standart_number="BML" group="groupC" category="cat3">
      <name>Бурмила</name>
      <country capital="" official_language="" time_zone="UTC/GMT  +2 hours" currency="" country_code="JAP">
        <country_name></country_name>
        <country_continent></country_continent>
        <country_government_type></country_government_type>
      </country>
      <year_of_establishment>1949</year_of_establishment>
      <head>кръгла, но е по-дълга, отколкото широка.</head>
      <ears>Широко поставените уши са със среден размер, широки в основата и постепенно изтъняващи и закръглени накрая.</ears>
      <eyes>много кръгли и широко поставени, под лек наклон към носа.</eyes>
      <tail>1.Тип rumру (код 51) - няма опашни прешлени и е налице пълна липса на опашка, като има вдлъбнатина на мястото на липсващата опашка, която се констатира с поставяне на палеца;
			2.Тип rumpy-riser (код 52) - с малко опашни прешлени, които обикновено са свързани неподвижно - представлява къс изправен израстък;
			3.Тип stumpy (код 53) - остатъчна къса опашка с деформации (удебеления);
			4.Тип longy (код 54) - опашката се доближава до нормалната дължина, но е видимо по-къса.</tail>
      <colors>
        <primary_color>сребриск</primary_color>
        <secondary_color>златист</secondary_color>
        <prefered_color>бял</prefered_color>
      </colors>
      <fur>къса</fur>
      <image>http://www.kotkite.com/img/articles/thumbs/0208070837_6_.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality></personality>
    </cat_breed>
	
	<cat_breed standart_number="KOR" group="groupC" category="cat4">
      <name>Корат</name>
	  <country capital="Кайро" official_language="арабски" time_zone="UTC/GMT  +2 hours" currency="египетска лира" country_code="EGP">
	    <country_name>Египет</country_name>
	    <country_continent>Африка</country_continent>
	    <country_government_type>република</country_government_type>
	  </country>
      <year_of_establishment>2002</year_of_establishment>
      <head></head>
      <ears>Характерни са големите уши</ears>
      <eyes> Очите са искрящо сини на цвят.</eyes>
      <tail></tail>
      <colors>
        <primary_color></primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>голо тяло</fur>
      <image>http://e4p-bg.com/wp-content/uploads/2014/09/Sphynx_1.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Ако сте решили да си вземете такава котка, не забравяйте – тя не счита себе си за котка! </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки 4</category>
    <category category_id="cat3">напълно разпознати котки 3</category>
  </categories>
  <groups>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>

=== yoanaB/ASP/XML_Files/XML_Cat/ASP_11_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fif SYSTEM "file:/D:/Documents/ASP/AspProject_YoanaBoyanova_71540_sourceCode/XML_Files/cat_breeds.dtd">
<fif>
  <cat_breeds>
    <cat_breed standart_number="TUV" group="groupB" category="cat1">
      <name>Турски ван</name>
      <country capital="" official_language="" time_zone="UTC/GMT  -2 hours" currency="" country_code="GBR">
        <country_name></country_name>
        <country_continent></country_continent>
        <country_government_type>кралство</country_government_type>
      </country>
      <year_of_establishment>1960</year_of_establishment>
      <head> Главата на Турски Ван е с формата на обърнат триъгълник.</head>
      <ears> Ушите на Турски Ван са едри и в тях може да има кичури козина. </ears>
      <eyes> Очите са разположени леко скосено и са овални.</eyes>
      <tail>опашката е дълга и пухкава.</tail>
      <colors>
        <primary_color>бял с червени петна</primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>Козината му е дълга и пухкава, искрящо бяла, с кафеникави или черни петна по главата.</fur>
      <image>http://gradcontent.com/lib/500x350/turkish-van1.jpg</image>
      <size>
        <males_size>8</males_size>
        <females_size>4</females_size>
      </size>
      <personality>котка с независим характер и понякога взима самостоятелни решения.</personality>
    </cat_breed>
	<cat_breed standart_number="ACL" group="groupC" category="cat4">
      <name>Американска дългокосместа</name>
	  <country capital="Кайро" official_language="арабски" time_zone="UTC/GMT  +2 hours" currency="египетска лира" country_code="EGP">
	    <country_name>Египет</country_name>
	    <country_continent>Африка</country_continent>
	    <country_government_type>република</country_government_type>
	  </country>
      <year_of_establishment>2000</year_of_establishment>
      <head></head>
      <ears>Характерни са големите уши</ears>
      <eyes> Очите са искрящо сини на цвят.</eyes>
      <tail></tail>
      <colors>
        <primary_color></primary_color>
        <secondary_color></secondary_color>
        <prefered_color></prefered_color>
      </colors>
      <fur>голо тяло</fur>
      <image>http://e4p-bg.com/wp-content/uploads/2014/09/Sphynx_1.jpg</image>
      <size>
        <males_size>5</males_size>
        <females_size>4</females_size>
      </size>
      <personality>Ако сте решили да си вземете такава котка, не забравяйте – тя не счита себе си за котка! </personality>
    </cat_breed>
  </cat_breeds>
  <categories>
    <category category_id="cat4">напълно разпознати котки 4</category>
	<category category_id="cat1">напълно разпознати котки 1</category>
  </categories>
  <groups>
    <group group_code="groupB">екзотични котки</group>
    <group group_code="groupC">късокосмести котки</group>
  </groups>
</fif>
