=== yoanaB/ASP/AspProjectApplication/Backup/AspProjectApplication/ASP_DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fci ( dog_breeds, sections, groups ) >
    <!ELEMENT dog_breeds (dog_breed+)>
        <!ELEMENT dog_breed (name,country,year_of_establishment,head,teeth,ears,eyes,tail,colors,fur,image,size,weight)>
             <!ATTLIST dog_breed standart_number ID #REQUIRED>
             <!ATTLIST dog_breed group IDREFS #REQUIRED>
             <!ATTLIST dog_breed section IDREFS #REQUIRED>
         <!ELEMENT name (#PCDATA)>
         <!ELEMENT country (country_name,country_continent,country_government_type)>
         <!ATTLIST country capital  CDATA #REQUIRED>
         <!ATTLIST country official_language CDATA #IMPLIED>
         <!ATTLIST country  time_zone  CDATA  #IMPLIED>
         <!ATTLIST country currency  CDATA #IMPLIED>
         <!ATTLIST country country_code CDATA #IMPLIED>
             <!ELEMENT country_name (#PCDATA)>
             <!ELEMENT country_continent (#PCDATA)>
             <!ELEMENT country_government_type (#PCDATA)>
             
         
         <!ELEMENT year_of_establishment (#PCDATA)>
         <!ELEMENT head (#PCDATA)>
         <!ELEMENT teeth (#PCDATA)>
         <!ELEMENT ears (#PCDATA)>
         <!ELEMENT  eyes (#PCDATA)>
         <!ELEMENT tail (#PCDATA)>
         <!ELEMENT colors (primary_color,secondary_color,prefered_color)>
            <!ELEMENT primary_color (#PCDATA)>
            <!ELEMENT secondary_color (#PCDATA)>
            <!ELEMENT prefered_color (#PCDATA)>
         <!ELEMENT fur (#PCDATA)>
         <!ELEMENT image (#PCDATA)>
            <!ELEMENT size (males_size,females_size)>
                <!ELEMENT males_size (#PCDATA)>
                <!ELEMENT females_size (#PCDATA)>
            <!ELEMENT weight (males_weight,females_weight)>
                <!ELEMENT males_weight (#PCDATA)>
                <!ELEMENT females_weight (#PCDATA)>
          
         <!ELEMENT sections (section+)>
            <!ELEMENT section (#PCDATA)>
                <!ATTLIST section section_id ID #REQUIRED>
         <!ELEMENT groups (group+)>
            <!ELEMENT group (#PCDATA)>
                <!ATTLIST group group_code ID #REQUIRED >

=== yoanaB/ASP/XML_Files/XML_Files/ASP_twelveth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN235" group="GR2" section="S2.2">
            <name>Немски дог</name>
            <country country_code="GER"  capital="Berlin" official_language="German" time_zone = "UTC/GMT +1 hour"  currency="Euro">
                <country_name>Гемрания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Демокративна и федерална република</country_government_type>
            </country>
            <year_of_establishment>1987</year_of_establishment>
            <head>
                Главата му е тежка като тази на мастифа. Върхът на черепа е почи напълно успореден с муцуната. Това придава на кучето царствен вид.
            </head>
            <teeth>  
                Челюстите са със здрави и бели зъби, правилно разположени, добре вкоренени в развитите челюсти. Захапката е ножицообразна – резците на горната челюст леко покриват резците на долната челюст, като при това се допират един до друг. Допуска се клещовидна захапка. Пастирите са предпочитали именно такава захапка. 
                Изисква се пълна зъбна формула, допуска се отсъствие на двата първи премоляра (2 х Р1), трети молари (М3) не се вземат в предвид.
            </teeth>
            <ears>
                Учите са поставени високо, средно големи, с предни ръбове, плътно лежащи към бузите. В спокойно състояние на кучето висят надолу.
                
            </ears>
            <eyes>
                Очите са средно големи, с бадемовидна форма. Прилягат плътно към клепачите.
                
            </eyes>
            <tail>
                Опашката е високо поставена и дълга, приличаща на сабя. 
                В спокойно състояние е отпусната надолу, а при възбуда и движение – се повдига над продължението на гръбната линия. 
            </tail>
            <colors>
                <primary_color>синя окраска или черна</primary_color>
                <secondary_color>тигрова окраска или петниста</secondary_color>
                <prefered_color> И двете разновидности са приемливи</prefered_color>
            </colors>
            <fur> 
                Немският дог е с късокосмест вид на космената покривка. 
                Космите са къси, гъсти, гладки, лъскави и плътно прилягат към тялото.
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!293</image>
            <size>
                <males_size> най - малко 80 см </males_size>
                <females_size>  най - малко 72 см</females_size>
            </size>
            <weight>
                <males_weight>50 - 70 кг  </males_weight>
                <females_weight>50 - 65 кг  </females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN1" group="GR7" section="S7.2">
            <name>Английски пойнтер</name>
            <country country_code="GBR"  capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
                <country_name>Великобритания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Монархия</country_government_type>
            </country>
            <year_of_establishment>2009</year_of_establishment>
            <head>
                Череп: Със средна ширина, в пропорция с дължината на муцуната. Ясно изразена окципитална кост.
                Стоп: Ясно изразен.
            </head>
            <teeth>  
                Челюст и зъби: Челюстите са силни, с перфектна, 
                симетрична и пълна ножична захапка, т.е. горните резци срещат долните в много тесен контакт и са разположени перпендикулярно на челюстите.
            </teeth>
            <ears>
                С тънка кожа, сравнително високо поставени, висящи, прилегнали по главата, умерено дълги, леко заострени в краищата си.
                
            </ears>
            <eyes>
                На равно разстояние от тила и носната гъба, със сияйно и добродушно изражение. Очите са с цвят на лешник, в съответствие с цвета на козината. Нито изпъкнали, нито широко отворени, нито гледащи под нивото на носа.
                Очните ръбове са тъмни, но може да са по-светли в случаите на лимонено и бяло оцветени кучета.
                
            </eyes>
            <tail>
                Със средна дължина, дебела в основата си, изтъняваща към върха. Опашката е добре покрита с гъсти косми. 
                Кучето я държи на нивото на гърба, без да я извива нагоре.
                При движение, опашката трябва да се размахва в страни.
            </tail>
            <colors>
                <primary_color>лимонено с бяло, оранжево с бяло</primary_color>
                <secondary_color> лешниково с бяло, и черно с бяло</secondary_color>
                <prefered_color> И двете разновидности са приемливи</prefered_color>
            </colors>
            <fur> 
                Косъм: Фин, къс, твърд и равномерно разположен, идеално гладък и прав, с безспорен блясък.
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!301</image>
            <size>
                <males_size>64-69 см </males_size>
                <females_size> 61-66 см</females_size>
            </size>
            <weight>
                <males_weight>Около 20 кг </males_weight>
                <females_weight>Около 18 кг </females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S2.2">Догообразни</section>
        <section section_id="S7.2">Британски и ирландски пойнтери и сетери</section>
    </sections>
    <groups>
        <group group_code="GR7">ПТИЧАРИ</group>
        <group group_code="GR2">ПИНЧЕРИ И ШНАУЦЕРИ. ДОГООБРАЗНИ И ШВЕЙЦАРСКИ ПАСТИРСКИ КУЧЕТА</group>
    </groups>
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/first_well_formed_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
    <dog_breeds>
        <dog_breed standart_number="SN270" group="GR5" section="S5.1">
            <name>Сибирско хъски</name>
            <country country_code="USA"  capital="Washington" official_language="American English"  time_zone = "UTC/GMT -5 hours"  currency="American Dollar">
                <country_name>САЩ</country_name>
                <country_continent>Северна Америка</country_continent>
                <country_government_type>Конституционна федерална република</country_government_type>
            </country>
            <year_of_establishment>2000</year_of_establishment>
            <head>
                Череп: Среден на размер и в съответствие с пропорциите на тялото,
                леко заоблен отгоре и се стеснява от най-широката си част към очите
                Стоп: Добре изразен
                Нос: Черен при сивите, бронзовите и черните кучета; с цвят на черен дроб при медночервените; може да бъде с телесен цвят при чисто белите кучета. Приемлив е "снежен нос" с розови ивици
                Муцуна: Средно дълга и средно широка, постепенно се стеснява към носа, връхчето нито е заострено, нито затъпено. От стопа и до върха носният гребен е прав.
                Устни: Добре пигментирани и плътно прилепнали
            </head>
            <teeth>
                Захапката е ножична.
            </teeth>
            <ears>
                Средни по размер, с триъгълна форма, плътно прилепнали и поставени високо на главата.
                Те са дебели, добре окосмени, леко засводени отзад и твърдо изправени, с леко заоблени връхчета, сочещи право нагоре.
            </ears>
            <eyes>
                С бадемовидна форма, средно раздалечени и поставени малко косо.
                Очите могат да бъдат кафеви или сини на цвят, приемливи са също по едно око от цвят или разноцветни (партиколор)
            </eyes>
            <tail>
                Добре окосмената опашка е с форма на четка за прах и е поставена точно под нивото на горната линия.
                Обикновено се носи над гърба в благороден сърп, когато кучето е нащрек. Когато е вдигната, опашката не се навива отстрани на тялото, нито прилепва плътно към гърба.
                Отпусната на нивото на гърба или под него опашка е нормална за кучето, когато е в покой. Космите по опашката са средно дълги и приблизително с една и съща дължина отгоре, отстрани и отдолу, като й придават вид на заоблена четка.
            </tail>
            <colors>
                <primary_color>Черно с бели петна или Бяло с черни петна</primary_color>
                <secondary_color>Чисто бяло или Чисто черно</secondary_color>
                <prefered_color>И двете разновидности са допустими и са с еднакъв приоритет</prefered_color>
            </colors>
            <fur>
                Косъмът на сибирското хъски е двоен и средно дълъг, като му придава вид на добре окосмено куче, но никога не е толкова дълъг, че да закрие ясните очертания на силуета на кучето.
                Подкосъмът е мек и гъст, и достатъчно дълъг, за да поддържа покривния косъм. Космите на покривния косъм са прави и донякъде прилепнали, но никога груби или щръкнали встрани от тялото.
                Трябва да се отбележи, че отсъствието на подкосъм по време на смяната на козината е нормално. Тримингът на мустаците и козината между пръстите и около лапите за придаване на по-спретнат вид е допустим.
                Тримингът на козината в която и да е друга част на кучето не трябва се прощава и се наказва много строго.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!298</image>
            <size>
                <males_size>53.5 до 60 см измерено при холката</males_size>
                <females_size>50.5 до 56 см измерено при холката</females_size>
            </size>
            <weight>
                <males_weight>20.5 до 28 кг</males_weight>
                <females_weight>15.5 до 23 кг</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN5" group="GR8" section="S8.2">
            <name>Кокер Шпаньол</name>
            <country country_code="GBR"  capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
                <country_name>Великобритания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Монархия</country_government_type>
            </country>
            <year_of_establishment>2003</year_of_establishment>
            <head>
                Череп: Добре развит, ясно очертан, нито много фин, нито много груб. 
                Стоп: Отчетлив, разположен в средата между върха на муцуната и тила.
            </head>
            <teeth>  
                Челюсти и зъби: Силни челюсти с перфектна, пълна и завършена ножична захапка, 
                т.е. горните резци плътно припокриват долните, и са перпендикулярни на челюстите.
            </teeth>
            <ears>
                Лобулни, ниско поставени, на нивото на очите. С фина кожа, достигащи върха на носа. Добре покрити с дълги, прави, коприноподобни косми. 
                
            </ears>
            <eyes>
                Пълни, но не изпъкнали. Тъмно кафeви или кафeви, никога светли, но в случаите на червенокафeви, пъстрo червенокафeви или червенокафeви с бяло на цвят кучета, цвят тъмен лешник може да хармонизира с козината. 
                Очите излъчват интелигентност и нежност, но са много будни, блестящи и жизнени. С изпънати ръбове.
                
            </eyes>
            <tail>
                Поставена леко под линията на гърба. Трябва весело да се размахва при движение и се носи хоризонтално, но никога нагоре. Обикновено купирана. 
                
            </tail>
            <colors>
                <primary_color>Черно</primary_color>
                <secondary_color>Шарени</secondary_color>
                <prefered_color>При едноцветните не е позволено бяло</prefered_color>
            </colors>
            <fur> 
                Гладък, с коприноподобна структура, никога твърд или вълнист, без да е твърде обилен и никога къдрав. 
                Добре окосмени предни крайници, тяло и задни крайници над скакателните стави. 
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!296</image>
            <size>
                <males_size>39 - 41 см </males_size>
                <females_size> 38 - 39 см</females_size>
            </size>
            <weight>
                <males_weight>12-15 кг </males_weight>
                <females_weight>12-14 кг </females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S5.1">Северни впрегатни породи</section>
        
        <section section_id="S8.2">Претърсващи кучета, С работен изпит </section>
    </sections>
    <groups>
        <group group_code="GR5"> Шпицове и примитивни породи</group>
        <group group_code="GR8"> Апортиращи, претърсващи и водни кучета</group>
    </groups>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_fourteenth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        
        <dog_breed standart_number="SN309" group="GR2" section="S2.2">
            <name>Шарпей</name>
            <country country_code="CHN" capital="Beijing" official_language="Chinesse" time_zone = "UTC/GMT +8 hours"  currency="Chinese Yuan">
                <country_name>Китай</country_name>
                <country_continent>Азия</country_continent>
                <country_government_type>Комунистически Щат</country_government_type>
            </country>
            <year_of_establishment>1999</year_of_establishment>
            <head>
                Главата има крушовидна форма. Сравнително тежка е и закръглена в основата.
                
                
                
            </head>
            <teeth>
                Клещовидна захапна (допуска се и ножична).Като цяло не е масивна
            </teeth>
            <ears>
                Ушите също са малки и имат форма на равнобедрен триъгълник. Върховете им са леко заоблени.
                
            </ears>
            <eyes>
                Очите са малки и с бадемовина форма.
            </eyes>
            <tail>
                Опашката е много високо поставена. В резултат на това се е разпространил и изразът "Анусът на Шарпея гледа към небето".
                В основата е по - дебела, а към върха изтънява. Може да се носи навита върху гърба или да е завита отстрани.
                
            </tail>
            <colors>
                <primary_color>Светло Бежав или червеникав</primary_color>
                <secondary_color>Сив или кафяв</secondary_color>
                <prefered_color> И двете разновидности са енакво ценени</prefered_color>
            </colors>
            <fur>
                Породата се отличава с доста груба, права и къса козина. Грубата му кожа е била създадена с цел да го защитава от различни нападатели.
                                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!315</image>
            <size>
                <males_size>40-51 см</males_size>
                <females_size> 38-49 см</females_size>
            </size>
            <weight>
                <males_weight>20 кг</males_weight>
                <females_weight>18-20 кг</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN328" group="GR2" section="S2.2">
            <name>Кавказка овчарка</name>
            <country country_code="RUS" capital="Moscow" official_language="Russian" time_zone = "UTC/GMT +3 hours"  currency="Russian Ruble">
                <country_name>Русия</country_name>
                <country_continent>Азия</country_continent>
                <country_government_type>Федерация</country_government_type>
            </country>
            <year_of_establishment>1996</year_of_establishment>
            <head>
                Череп: Масивна с широка черепна част и силно развити скули глава. Широко чело, плосък, разделен на две половини от неголяма бразда.
                Стоп: Стопът не е отчетливо изразен.                
                
                
            </head>
            <teeth>
                Бели, здрави, добре развити, плътно прилегнали един към друг, без видими празнини. Резците са равно разположени в основата – ножична захапка.
            </teeth>
            <ears>
                Висящи, високо поставени, късо купирани.                
            </ears>
            <eyes>
                Тъмни, малки, с овална форма, дълбоко поставени..
            </eyes>
            <tail>
                Високо поставена, ниско спусната, достигаща скакателните стави. Сърповидна, на кука или навита в кръг. Допуска се купиране на опашката.
                
            </tail>
            <colors>
                <primary_color>Зонарно сиви</primary_color>
                <secondary_color>Зонарно черни</secondary_color>
                <prefered_color> И двете разновидности са енакво ценени</prefered_color>
            </colors>
            <fur>
                Косъмът е прав, груб, със силно развит подкосъм, по-светъл на цвят. По главата и предната част на крайниците, косъма е по-къс и плътно прилепнал.
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!316</image>
            <size>
                <males_size>над 65 см</males_size>
                <females_size> над 62 см</females_size>
            </size>
            <weight>
                <males_weight>над 35 кг</males_weight>
                <females_weight>над 34 кг</females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        
        <section section_id="S2.2">Догообразни</section>
    </sections>
    <groups>
        <group group_code="GR2">ПИНЧЕРИ И ШНАУЦЕРИ. ДОГООБРАЗНИ И ШВЕЙЦАРСКИ ПАСТИРСКИ КУЧЕТА</group>
    </groups>
    
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_third_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN120" group="GR7" section="S7.2">
            <name>Ирландски сетер</name>
            <country country_code="IRL"  capital="Dublin" official_language="British English/Irish" time_zone = "No UTC/GMT offset"  currency="Pound">
                <country_name>Ирландия</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Част от монархията Великобритания</country_government_type>
            </country>
            <year_of_establishment>1878</year_of_establishment>
            <head>
                Издължена и суха, без да е груба при ушите. Муцуната и черепа са с еднаква дължина и с паралелни линии.
            </head>
            <teeth>
                Челюстите са с определено еднаква дължина.Захапката е ножична
            </teeth>
            <ears>
                Средно големи, с фина структура, разположени ниско и доста назад, висящи, без гънки, плътно по главата.
            </ears>
            <eyes>
                Тъмен лешник или тъмно кафеви, без да бъдат много големи.
            </eyes>
            <tail>
                Умерено дълга, пропорционална на размера на тялото, поставена по-скоро ниско, силна в основата, изтъняваща до фина на върха.
                Носи се на или под нивото на гърба.
            </tail>
            <colors>
                <primary_color>Едноцветна махагоновотъмночервена</primary_color>
                <secondary_color>Едноцветна махагоновотъмночервена с бели петна по гърдите и лицевата част</secondary_color>
                <prefered_color>Едноцветна махагоновотъмночервена</prefered_color>
            </colors>
            <fur> По главата, предната част на краката и краищата на ушите - къс и фин; върху останалите части на тялото и краката умерено дълъг, гладък и толкова свободен, колкото е възможно.
                Покривните косми по външната част на ушите са дълги и коприненоподобни; по задната част на предните и задните крайници, дълги и фини.
                Наличната козина по корема образува ресни, които могат да се разпрострат до гърдите и гърлото.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!297</image>
            <size>
                <males_size>58-67 см. в холката</males_size>
                <females_size>55-62 см. в холката</females_size>
            </size>
            <weight>
                <males_weight>25-30 кг.</males_weight>
                <females_weight>20-25 кг.</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN143" group="GR2" section="S2.1">
            <name>Доберман</name>
            <country country_code="GER"  capital="Berlin" official_language="German" time_zone = "UTC/GMT +1 hour"  currency="Euro">
		        <country_name>Гемрания</country_name>
		        <country_continent>Европа</country_continent>
		        <country_government_type>Демокративна и федерална република</country_government_type>
		    </country>
            <year_of_establishment>1994</year_of_establishment>
            <head>
               ЧЕРЕПНА ЧАСТ: Силна и в хармония с тялото. Гледана отгоре, главата има формата на тъп клин.
            </head>
            <teeth>
               Силни широки горна и долна челюст, ножицовидна захапка, 42 правилно разположени зъба с нормални размери.
            </teeth>
            <ears>
               Ушите, които са високо поставени, се носят изправени и купирани с дължина в съответствие с пропорциите на главата. 
			   В държави, където купирането не е разрешено, некупираните уши се приемат равностойно.
            </ears>
            <eyes>
                Средно големи, овални и тъмни на цвят. По-светли тонове се разрешават при кафевите кучета. Плътно затварящи се клепачи. Клепачите трябва да са покрити с козина. 
				Силно нежелана е плешивост около ръба на окото.
            </eyes>
            <tail>
                Тя е високо поставена и късо купирана като приблизително два опашни прешлена се оставят видими. 
				В държавите, където купирането не е разрешено, опашката може да остане в естествен вид.
            </tail>
            <colors>
                <primary_color>Черно с кафеви петна</primary_color>
                <secondary_color>Кафяво с тъмно червени петна</secondary_color>
                <prefered_color>Черно с кафеви петна</prefered_color>
            </colors>
            <fur> 
			Козината е къса, твърда и гъста. Тя е прилепналаплътно, гладка е и е равномерно разпределена по цялата повърхност на тялото.
			Подкосъм не се допуска.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!302</image>
            <size>
                <males_size>60-67 см. в холката</males_size>
                <females_size>55-65 см. в холката</females_size>
            </size>
            <weight>
                <males_weight>35-43 кг.</males_weight>
                <females_weight>30-35 кг.</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN86" group="GR3" section="S3.4">
            <name>Йоркшир Териер</name>
            <country country_code="GBR"  capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
		        <country_name>Великобритания</country_name>
		        <country_continent>Европа</country_continent>
		        <country_government_type>Монархия</country_government_type>
		    </country>
            <year_of_establishment>2003</year_of_establishment>
            <head>
               Череп:До известна степен малък и плосък, не много издаден или закръглен.
            </head>
            <teeth>
                Перфектна, нормална и напълно затваряща се захапка, в смисъл горните зъби покриват долните. 
				Добре разположени зъби с равни челюсти.
            </teeth>
            <ears>
               Малки, във формата на буквата "V", изправени не много раздалечени едно от друго, 
			   покрити с къса козина цвета е много дълбоко и богато жълтокафяв.
            </ears>
            <eyes>
                Средни, тъмни, искрящи със остро интелигентно излъчване и разположени да гледат точно напред. 
				Не са изпъкнали.Ръба на клепача е тъмен.
            </eyes>
            <tail>
                Неподрязана, с много козина, по-тъмно синя от останалата част от тялото, особено на края на опашката. Трябва да се държи на височина малко по-висока от равнината на гърба, 
				така че да придава вид на добре балансирана външност.
            </tail>
            <colors>
                <primary_color>Тъмно стоманено синьо</primary_color>
                <secondary_color>Няма разновидност</secondary_color>
                <prefered_color>Тъмно стоманено синьо</prefered_color>
            </colors>
            <fur> 
			 По тялото умерено дълга, перфектно права (в никакъв случай не на вълнички),лъскава, изглеждаща като финна коприна, не като вълна. 
			 Спуска се по дължина на главата, с богат златен цвят, по-дълбок като цвят от страни на главата, корените не ушите и муцуната където трябва да е много дълга. 
			 Цветът на главата не трябва да продължава по врата, нито тъмни или опушени косми да се смесват със златистия цвят.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!287</image>
            <size>
                <males_size>При тази порода само теглото има значение</males_size>
                <females_size>При тази порода само теглото е от значение</females_size>
            </size>
            <weight>
                <males_weight> Тегло до 3.1 кг (7 паунда).</males_weight>
                <females_weight> Тегло до 3.1 кг (7 паунда).</females_weight>
            </weight>
        </dog_breed>
		
    </dog_breeds>
    <sections>
        <section section_id="S7.2">Британски и ирландски пойнтери и сетери</section>
        <section section_id="S2.1"> Пинчери и шнауцери</section>
        <section section_id="S3.4"> Тойтериери</section>
	</sections>
    <groups>
        <group group_code="GR7"> ПТИЧАРИ</group>
        <group group_code="GR2"> ПИНЧЕРИ И ШНАУЦЕРИ. ДОГООБРАЗНИ И ШВЕЙЦАРСКИ ПАСТИРСКИ КУЧЕТА</group>
        <group group_code="GR3">ТЕРИЕРИ</group>
	</groups>
</fci>
