=== yoanaB/ASP/AspProjectApplication/Backup/AspProjectApplication/ASP_DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fci ( dog_breeds, sections, groups ) >
    <!ELEMENT dog_breeds (dog_breed+)>
        <!ELEMENT dog_breed (name,country,year_of_establishment,head,teeth,ears,eyes,tail,colors,fur,image,size,weight)>
             <!ATTLIST dog_breed standart_number ID #REQUIRED>
             <!ATTLIST dog_breed group IDREFS #REQUIRED>
             <!ATTLIST dog_breed section IDREFS #REQUIRED>
         <!ELEMENT name (#PCDATA)>
         <!ELEMENT country (country_name,country_continent,country_government_type)>
         <!ATTLIST country capital  CDATA #REQUIRED>
         <!ATTLIST country official_language CDATA #IMPLIED>
         <!ATTLIST country  time_zone  CDATA  #IMPLIED>
         <!ATTLIST country currency  CDATA #IMPLIED>
         <!ATTLIST country country_code CDATA #IMPLIED>
             <!ELEMENT country_name (#PCDATA)>
             <!ELEMENT country_continent (#PCDATA)>
             <!ELEMENT country_government_type (#PCDATA)>
             
         
         <!ELEMENT year_of_establishment (#PCDATA)>
         <!ELEMENT head (#PCDATA)>
         <!ELEMENT teeth (#PCDATA)>
         <!ELEMENT ears (#PCDATA)>
         <!ELEMENT  eyes (#PCDATA)>
         <!ELEMENT tail (#PCDATA)>
         <!ELEMENT colors (primary_color,secondary_color,prefered_color)>
            <!ELEMENT primary_color (#PCDATA)>
            <!ELEMENT secondary_color (#PCDATA)>
            <!ELEMENT prefered_color (#PCDATA)>
         <!ELEMENT fur (#PCDATA)>
         <!ELEMENT image (#PCDATA)>
            <!ELEMENT size (males_size,females_size)>
                <!ELEMENT males_size (#PCDATA)>
                <!ELEMENT females_size (#PCDATA)>
            <!ELEMENT weight (males_weight,females_weight)>
                <!ELEMENT males_weight (#PCDATA)>
                <!ELEMENT females_weight (#PCDATA)>
          
         <!ELEMENT sections (section+)>
            <!ELEMENT section (#PCDATA)>
                <!ATTLIST section section_id ID #REQUIRED>
         <!ELEMENT groups (group+)>
            <!ELEMENT group (#PCDATA)>
                <!ATTLIST group group_code ID #REQUIRED >

=== yoanaB/ASP/XML_Files/XML_Files/ASP_fourth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
       
     <dog_breed standart_number="SN161" group="GR6" section="S6.1">
            <name>Бийгъл</name>
         <country  country_code="GBR" capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
		        <country_name>Великобритания</country_name>
		        <country_continent>Европа</country_continent>
		        <country_government_type>Монархия</country_government_type>
		    </country>
            <year_of_establishment>1990</year_of_establishment>
            <head>
Породата се отличава с  добро телосложение. Главата е с умерена дължина и пропорционална на тялото.
           </head>
            <teeth>  
			Челюстите трябва да са здрави, с перфектна, правилна и завършена ножична захапка.
            </teeth>
            <ears>
                Ушите им са доста широки, дълги и висящи, със заоблени върхове. С дължината им средно 18 см те улавят миризмите и ги задържат близо до носа.
				Ушите и носът им са като Батман и Робин. 
				Без тях Биглите няма да са "супер гончетата", които всички познават.




            </ears>
            <eyes>
			Очите им не са поставени много дълбоко и имат добродушно изражение.

           </eyes>
            <tail>
               Опашката е поставена високо. Има средна дължина. Здрава и сравнително дебела е.

            </tail>
            <colors>
                <primary_color>Лимонено - жълта и бяла</primary_color>
                <secondary_color>Жълтеникаво - кафява и бяла</secondary_color>
                <prefered_color> И двете разновидности са приемливи</prefered_color>
            </colors>
            <fur> 
			Биглите имат лъскава, гладка и сравнително къса космена покривка, която е с твърд горен слой.
			В долната част на опашката косъмът е малко по - дълъг.

            </fur>
         <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!309</image>
            <size>
                <males_size>33 - 41 см </males_size>
                <females_size> 33 - 41 см</females_size>
            </size>
            <weight>
                <males_weight>Около 17 кг </males_weight>
                <females_weight>Около 15 кг </females_weight>
            </weight>
        </dog_breed>
		
      <dog_breed standart_number="SN153" group="GR6" section="S6.3">
            <name>Далматинец</name>
		    <country country_code="CRO"  capital="Zagreb" official_language="Croatian" time_zone = "UTC/GMT +1 hour"  currency="Kuna">
		        <country_name>Далмация/Република Хърватска</country_name>
		        <country_continent>Европа</country_continent>
		        <country_government_type>Унитарна парламентарна конституциална република</country_government_type>
		    </country>
            <year_of_establishment>1985</year_of_establishment>
            <head>
Отличават се със стегнато тяло и силно развити мускули. Главата им е умерено широка.
			</head>
            <teeth>  
			 Челюстите са с ножицовидна захапка.
            </teeth>
            <ears>
                Ушите са средно дълги, висящи и леко клепнали.

            </ears>
            <eyes>
			Имат средни по размер очи, които са с  кръгла форма.

           </eyes>
            <tail>
               Опашката е дълга, като в основата е по - дебела, а към края изтънява.
				Носи се над гърба, а когато опашката е отпусмата, придобива саблевидна форма и стига до скакателните стави.
            </tail>
            <colors>
                <primary_color>Бяло с черни петна</primary_color>
                <secondary_color>Бяло с кафеви петна</secondary_color>
                <prefered_color> Бяло с черни петна</prefered_color>
            </colors>
            <fur> 
			Всички Далматинци са с къса и прилепнала към тялото козина. Космената покривка е гладка, гъста, твърда и лъскава, плътно покриваща цялото тяло.
            </fur>
		    <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!303</image>
            <size>
                <males_size>56 - 61 см </males_size>
                <females_size> 54 - 59 см</females_size>
            </size>
            <weight>
                <males_weight>27 - 32 кг </males_weight>
                <females_weight>24 - 29 кг </females_weight>
            </weight>
		</dog_breed>
       
       
    </dog_breeds>
    <sections>
        <section section_id="S6.1">Гончета (следотърсачи)</section>
        <section section_id="S6.3">Подобни породи</section>
       
    </sections>
    <groups>
       
        <group group_code="GR6">ГОНЧЕТА (СЛЕДОТЪРСАЧИ) И ДРУГИ ПОДОБНИ ПОРОДИ</group>
      

	</groups>
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_first_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN243" group="GR5" section="S5.1">
            <name>Аляски маламут</name>
            <country country_code="USA"  capital="Washington" official_language="American English"  time_zone = "UTC/GMT -5 hours"  currency="American Dollar">
                <country_name>САЩ</country_name>
                <country_continent>Северна Америка</country_continent>
                <country_government_type>Конституционна федерална република</country_government_type>
            </country>
            <year_of_establishment>1996</year_of_establishment>
            <head>
                Главата е широка и мощна, не груба и тежка, а в пропорция с размера на кучето. Изражението е меко и показва дружелюбното му отношение.
                ЧЕРЕПНА ЧАСТ:
                Череп: Широк и средно заоблен между ушите, като постепенно се стеснява и изравнява отгоре с приближаването към очите, а се заобля към бузите. Между очите има лека бразда. Горната линия на черепа и тази на муцуната при съединяването си образуват лек наклон надолу от правата линия.
                Стоп: Плитък
            </head>
            <teeth>
                Широки, с големи зъби. Резците се срещат в ножична захапка. Обратна или клещовидна захапка е порок.
            </teeth>
            <ears>
                Средноголеми, но малки в съотношение с главата. Ушите са триъгълни по форма и леко заоблени на връхчетата. 
                Те са поставени доста широко по външния заден ръб на черепа на една линия с горния край на окото, като по този начин, когато са наострени, изглеждат сякаш се "разклоняват" от черепа. Наострените уши са насочени леко напред, но когато кучето работи, 
                ушите често са притиснати към черепа. Високо поставените уши са недостатък.
            </ears>
            <eyes>
                Kафяви, бадемовидни, умерено големи, косо поставени. Предпочита се очите да са тъмни. Сините очи са порок. 
                Разположението на очите придава вълчи поглед, но същевременно е мек и дружелюбен.
            </eyes>
            <tail>
                Поставена е така, че се явява продължение на гръбначния стълб, спусната или вдигната над гърба, по форма не е подобна на лисича и не образува плътен пръстен, а по-скоро напомня на развято украшение от пера.
            </tail>
            <colors>
                <primary_color>Вълчи цвят</primary_color>
                <secondary_color>Черно с бяло</secondary_color>
                <prefered_color>И двете разновидности са допустими и са с еднакъв приоритет</prefered_color>
            </colors>
            <fur>
                Трябва да има гъст и твърд покривен космен слой. Подкосмието е плътно, с дължина от 2,5 см до 5 см, мазно и пухкаво. 
                Около врата връхния космен слой е изправен и образува гъста пухкава „яка”. 
                Дължината на козината и подкосмието се мени на различните участъци на тялото – отстрани е къса, а на врата, на рамената, по цялата дължина на гърба и поясницата,
                на задните страни на задните крака и на опашката, е по-дълга.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!295</image>
            <size>
                <males_size>63.5  см измерено при холката</males_size>
                <females_size>58 см измерено при холката</females_size>
            </size>
            <weight>
                <males_weight>38 кг</males_weight>
                <females_weight>34 кг</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN212" group="GR5" section="S5.1">
        <name>Самоед</name>
            <country country_code="RUS"  capital="Moscow" official_language="Russian"  time_zone = "UTC/GMT +4 hours"  currency="Russian Ruble">
                <country_name>Русия</country_name>
                <country_continent>Евро-Азия</country_continent>
                <country_government_type>Федерация</country_government_type>
            </country>
        <year_of_establishment>1909</year_of_establishment>
        <head>
            Мощна и клиновидна по форма.
            Черепна област:
            Череп: Когато се гледа отпред и отстрани, единствено леко изпъкнал. Широк между ушите. Леко забележима бразда между очите.
            Стоп: Ясно очертан, но немного изразен.
        </head>
        <teeth>
            Съвършена и пълна ножична захапка. Здрави и силни зъби, и челюсти. Нормална зъбна формула.
        </teeth>
        <ears>
            Изправени, по-скоро малки, дебели, триъгълни и леко заоблени във върховете. 
            Те трябва да бъдат подвижни, високо поставени.
            Благодарение на широкия череп са подобаващо раздалечени.
        </ears>
        <eyes>
            Тъмно кафеви на цвят, добре поставени в орбитите си, по-скоро раздалечени,
            до известна степен коси и с бадемовидна форма. Изражението е "усмихващо се", 
            добродушно, жизнено и интелигентно. Очните ръбове са черни.
        </eyes>
        <tail>
            Поставена по-скоро високо. Когато кучето е възбудено или се движи, опашката се носи вдигната върху гърба или отстрани.
            Може да е висяща при покой, като тогава трябва да достига до скакателните стави.
        </tail>
        <colors>
            <primary_color>Чисто бял, кремав</primary_color>
            <secondary_color>Бял с бисквитен отенък</secondary_color>
            <prefered_color>Чисто бял</prefered_color>
        </colors>
        <fur>
            Обилна, дебела, пухкава и гъста покривна козина. Самоеда е куче с двуслойна космена покривка с мек и гъст подкосъм и по-дълъг, по-груб и прав покриващ косъм. 
            Козината трябва да оформя яка около шията и плешките, най-добре проявени при мъжките. 
            По главата и предната страна на крайниците козината е къса и гъста. По външната част на ушите, къса, права и гладка.
        </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!288</image>
        <size>
            <males_size>57 см измерено при холката</males_size>
            <females_size>53 см измерено при холката</females_size>
        </size>
        <weight>
            <males_weight>32 кг</males_weight>
            <females_weight>29 кг</females_weight>
        </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S5.1">Северни впрегатни породи</section>
    </sections>
    <groups>
        <group group_code="GR5">ШПИЦОВЕ И ДРУГИ ПРИМИТИВНИ ПОРОДИ</group>
     </groups>
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_seventeenth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN11" group="GR3" section="S3.3"> 
            <name>Бултериер</name>
            <country  country_code="GBR" capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
                <country_name>Великобритания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Монархия</country_government_type>
            </country>
            <year_of_establishment>1987</year_of_establishment>
            <head>Главата е дълга, силна и дълбока към края на муцуната, но не груба. Ако се гледа отпред тя е яйцевидна, добре запълнена без вдлъбнатини и неравности. 
                Горната част на черепа е почти плоска между ушите. Профилната линия е леко изпъкнала, спускайки се от върха на черепа до края на носа, който трябва да бъде черен и извит надолу. 
                Ноздрите са добре развити, долната челюст е дълбока и силна.</head>
            <teeth>
                Зъбите са здрави, чисти, силни, с добра големина, равномерно разположени с плътна захапка като ножица, 
                освен това горния ред зъби плътно покрива долния без наличие на празнини и зъбите са поставени в челюстите вертикално. 
                Устните са сухи и добре прилепнали. 
            </teeth>
            <ears>
                Малки, тънки, близко разположени помежду си. Кучето трябва да държи ушите си изправени право нагоре.
            </ears>
            <eyes>
                Изглеждат малки, тесни, косо поставени и триъгълни. Дълбоко поставени, черни или тъмнокафяви, с пронизващ блясък.
                Разстоянието от края на носа до очите е видимо по-голямо отколкото от очите до края на черепа. Сини или частично сини очи са нежелателни.
            </eyes>
            <tail>
                Къса, ниско поставена, носи се хоризонтално. Дебела в основата, изтъняваща към края.
            </tail>
            <colors>
                <primary_color> Бяло</primary_color>
                <secondary_color>Бяло с петна по главата</secondary_color>
                <prefered_color>Бяло с петна по главата се предпочита</prefered_color>
            </colors>
            <fur>
                Къса, гладка, добре прилепнала и твърда, с идеален блясък. Кожата е плътно стегната. През зимата може да се появи мек подкосъм.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!325</image>
            <size>
                <males_size>Няма ограничение във височина но трябва да има строен вид</males_size>
                <females_size>Няма ограничение във височина но трябва да има строен вид</females_size>
            </size>
            <weight>
                <males_weight>Теглото не е от значение.Трябва да излъчва мощ.</males_weight>
                <females_weight>Теглото не е от значение.Трябва да излъчва мощ.</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN286" group="GR3" section="S3.3"> 
            <name>Стафорширски териер</name>
            <country country_code="USA"  capital="Washington" official_language="American English"  time_zone = "UTC/GMT -5 hours"  currency="American Dollar">
                <country_name>САЩ</country_name>
                <country_continent>Северна Америка</country_continent>
                <country_government_type>Конституционна федерална република</country_government_type>
            </country>
            <year_of_establishment>1997</year_of_establishment>
            <head>Средно дълга, череп дълбок и широк, подчертани челюсти ,добре изразен стоп , високо поставени уши.</head>
            <teeth>
                Добре очертани челюсти.Долна челюст -силна с добра захапка.Бърни-прилепнали , не висящи.Горните зъби трябва плътно да опират върху външната част на долните зъби
            </teeth>
            <ears>
                По-добре да не са купирани, но могат да бъдат и купирани.Некупираните уши трябва да бъдат къси и във вид на роза или полуизправени.Изцяло увисналите уши са дефект.
            </ears>
            <eyes>
                Тъмни и кръгли ,поставени ниско върху черепа и добре раздалечени.Клепачните цепки не трябва да са депигментирани.
            </eyes>
            <tail>
                Дебела в основата, изтъняваща към края.Къса в сравнение с ръста, ниско заловена, изтънява към съвсем тънък край ,не е извита, нито поставена на гърба.Не се купира.
            </tail>
            <colors>
                <primary_color> Едноцветна на петна</primary_color>
                <secondary_color>Двуцветна</secondary_color>
                <prefered_color>Равнопоставени са</prefered_color>
            </colors>
            <fur>
                Къса гъста, твърда на пипане и лъскава.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!326</image>
            <size>
                <males_size>46-48 см</males_size>
                <females_size>43-46 см.</females_size>
            </size>
            <weight>
                <males_weight>Теглото трябва да е пропорционално на ръста.</males_weight>
                <females_weight>Теглото трябва да е пропорционално на ръста.</females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S3.3">Бултериери</section>
    </sections>
    <groups>
        <group group_code="GR3"> ТЕРИЕРИ</group>
    </groups>
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_seventh_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN148" group="GR4" section="S4.1"> 
            <name>Дакел</name>
            <country country_code="GER"  capital="Berlin" official_language="German" time_zone = "UTC/GMT +1 hour"  currency="Euro">
                <country_name>Гемрания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Демокративна и федерална република</country_government_type>
            </country>
            <year_of_establishment>2001</year_of_establishment>
            <head>Издължена когато се гледа в профил и отгоре. Изострена равномерно към носната гъба, но без да става остра. Надочните дъги са ясно изразени. Хрущялите на носа и горната линя на муцуната са дълги и тесни.</head>
            <teeth>
                Горната и долната челюсти са добре развити. Ножична захапка, равна и плътно затворена. Идеален, пълен постав от 42 зъба в хармония с изискванията за устата на кучето, със здрави резци точно прилепени един към друг. 
            </teeth>
            <ears>
                Високо поставени, не много напред. Достатъчно дълги, но не прекалено. Заоблени, без да са тесни, остри или прегънати. Подвижни, с вътрешен ръб прилепнал по бузите.
                
            </ears>
            <eyes>
                Средно големи, овални, поставени доста раздалечени, едно от друго, с ясно, енергично и приятелско изражение. Не са пронизителни. Цветът е светло, тъмно червеникавокафяво до кафяво-черно при всички цветове на козината.
                Разноцветни, рибeни или бисерни очи при пъстрите кучета са допустими, но нежелани.
            </eyes>
            <tail>
                Поставена не много високо, носи се като продължение на горната линия.
                Приема се лека кривина в последната третина на опашката.
            </tail>
            <colors>
                <primary_color> черно с кафеви петна или изцяло черно</primary_color>
                <secondary_color>кафяво с червени петна или изцяло кафяво</secondary_color>
                <prefered_color>кафевият цвят се предпочита</prefered_color>
            </colors>
            <fur>
                Косъм: Къс, гъст, лъскав, подобаващо гладък, твърд и стегнат. Нито една част от тялото не трябва да е лишена от козина. 
                Опашка: С фини косми, цялостно, не толкова обилно окосмена. Малко по-дълги покривни косми по долната част не са недостатък.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!304</image>
            <size>
                <males_size>39 см. обиколка на гръдния кош</males_size>
                <females_size>37 см. обиколка на гръдния кош</females_size>
            </size>
            <weight>
                <males_weight>9.25 кг.</males_weight>
                <females_weight>9.05 кг.</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN255" group="GR5" section="S5.5"> 
            <name>Акита</name>
            <country country_code="JAP"  capital="Tokyo" official_language="Japanese" time_zone = "UTC/GMT +9 hours"  currency="Japanese Yenna">
                <country_name>Япония</country_name>
                <country_continent>Азия</country_continent>
                <country_government_type>Конституционна монархия</country_government_type>
            </country>
            <year_of_establishment>2000</year_of_establishment>
            <head>Акита ину имат здраво и набито телосложение. Тялото им е леко издължено, а главата е тежка. Видът им показва доста голям респект.
            </head>
            <teeth>
                Горната и долната челюсти са добре развити. Ножична захапка, равна и плътно затворена. Идеален, пълен постав от 42 зъба в хармония с изискванията за устата на кучето, със здрави резци точно прилепени един към друг. 
            </teeth>
            <ears>
                Ушите са тип "вълчи".  Не са много големи, но са доста дебели и плътни, с широка основа.
                
                По форма са триъгълни, като към върха са леко заоблени. Стоят изправени и наклонени леко напред.
                
            </ears>
            <eyes>
                Очите са малки и с почти триъгълна форма. Тя се дължи на издигането на външният очен ъгъл. Раздалечени са едно спрямо друго.
                
            </eyes>
            <tail>
                Имат характерна завита пухкава опашка.
                
                Завиването е под формата на пръстен, понякога e спирално навита, допираща се до гърба и бедрата.
            </tail>
            <colors>
                <primary_color> Едноцветна - бял. При белите Акита няма маска. Може също тигрова </primary_color>
                <secondary_color>Петниста оркаска</secondary_color>
                <prefered_color>Едноцветен бял с жълти петна или черни</prefered_color>
            </colors>
            <fur>
                Кучетата от тази порода имат двуслойна пухкава козина, която се състои от груб студоустойчив външен слой. Подкосмието е гъсто и меко.
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!311</image>
            <size>
                <males_size>65-70 см. в холката</males_size>
                <females_size>63 см. в холката</females_size>
            </size>
            <weight>
                <males_weight>45-50 кг.</males_weight>
                <females_weight>40-45 кг.</females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S4.1">Дакели с работен изпит</section>
        <section section_id="S5.5">Азиатски шпицове и подобни породи</section>
    </sections>
    <groups>
        <group group_code="GR4">ДАКЕЛИ</group>
        <group group_code="GR5">ШПИЦОВЕ И ДРУГИ ПРИМИТИВНИ ПОРОДИ</group>
    </groups>
</fci>
