=== yoanaB/ASP/AspProjectApplication/Backup/AspProjectApplication/ASP_DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fci ( dog_breeds, sections, groups ) >
    <!ELEMENT dog_breeds (dog_breed+)>
        <!ELEMENT dog_breed (name,country,year_of_establishment,head,teeth,ears,eyes,tail,colors,fur,image,size,weight)>
             <!ATTLIST dog_breed standart_number ID #REQUIRED>
             <!ATTLIST dog_breed group IDREFS #REQUIRED>
             <!ATTLIST dog_breed section IDREFS #REQUIRED>
         <!ELEMENT name (#PCDATA)>
         <!ELEMENT country (country_name,country_continent,country_government_type)>
         <!ATTLIST country capital  CDATA #REQUIRED>
         <!ATTLIST country official_language CDATA #IMPLIED>
         <!ATTLIST country  time_zone  CDATA  #IMPLIED>
         <!ATTLIST country currency  CDATA #IMPLIED>
         <!ATTLIST country country_code CDATA #IMPLIED>
             <!ELEMENT country_name (#PCDATA)>
             <!ELEMENT country_continent (#PCDATA)>
             <!ELEMENT country_government_type (#PCDATA)>
             
         
         <!ELEMENT year_of_establishment (#PCDATA)>
         <!ELEMENT head (#PCDATA)>
         <!ELEMENT teeth (#PCDATA)>
         <!ELEMENT ears (#PCDATA)>
         <!ELEMENT  eyes (#PCDATA)>
         <!ELEMENT tail (#PCDATA)>
         <!ELEMENT colors (primary_color,secondary_color,prefered_color)>
            <!ELEMENT primary_color (#PCDATA)>
            <!ELEMENT secondary_color (#PCDATA)>
            <!ELEMENT prefered_color (#PCDATA)>
         <!ELEMENT fur (#PCDATA)>
         <!ELEMENT image (#PCDATA)>
            <!ELEMENT size (males_size,females_size)>
                <!ELEMENT males_size (#PCDATA)>
                <!ELEMENT females_size (#PCDATA)>
            <!ELEMENT weight (males_weight,females_weight)>
                <!ELEMENT males_weight (#PCDATA)>
                <!ELEMENT females_weight (#PCDATA)>
          
         <!ELEMENT sections (section+)>
            <!ELEMENT section (#PCDATA)>
                <!ATTLIST section section_id ID #REQUIRED>
         <!ELEMENT groups (group+)>
            <!ELEMENT group (#PCDATA)>
                <!ATTLIST group group_code ID #REQUIRED >

=== yoanaB/ASP/XML_Files/XML_Files/ASP_ninth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN166" group="GR1" section="S1.1">
            <name>Немско овчарско куче</name>
            <country country_code="GER"  capital="Berlin" official_language="German" time_zone = "UTC/GMT +1 hour"  currency="Euro">
                <country_name>Гемрания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Демокративна и федерална република</country_government_type>
            </country>
            <year_of_establishment>1899</year_of_establishment>
            <head>Дължината на главата е пропорционална на големината на тялото и представлява 40 % от височината при холката.
                В общи линии главата трябва да е суха, с умерена ширина между ушите.
                Ширината на главата трябва да отговаря на нейната дължина.
                При мъжките е допустимо главата да е малко по-широка, а при женските да е малко по-тясна.
            </head>
            <teeth>Трябва да са здрави, силни и компактни (общо 42 зъба, от които 20 в горната челюст и 22 в долната челюст).
                Захапката е ножицоподобна.Недопустима е предна, задна или клещоподобна захапка, 
                а също така и по-големи разстояния между зъбите.
            </teeth>
            <ears>
                Средноголеми, широки в основата, високо поставени, стърчащи нагоре, заострени, насочени напред.
                Не трябва да са завити навътре. За недостатък се приемат клепналите, скъсените, а така също и насочените право нагоре уши.
                За недостатък се приема, когато кучето при движение, а понякога и когато лежи, прилепва ушите си към главата.
                До 6 месечна възраст, а понякога и до по-късно, ушите могат да бъдат увиснали или завити навътре.
            </ears>
            <eyes>
                Средноголеми с бадемовидна форма, леко косо поставени. Не трябва да са изпъкнали.
                Цветът им е според цвета на космената покривка, желателно да е тъмен.
                Погледът е жив, умен и самоуверен.
            </eyes>
            <tail>
                Богато окосмена, стигаща най-малко до скакателните стави. Не трябва да е по-дълга от средата на метатарзусите.
                Недопустима е влачещата се по земята опашка.
                Недопустими са отклоненията встрани. 
            </tail>
            <colors>
                <primary_color>Черна с равномерни кафяви, жълти до светлосиви петна</primary_color>
                <secondary_color>Изцяло черен цвят или Едноцветно сива</secondary_color>
                <prefered_color> Черна с равномерни кафяви, жълти до светлосиви петна </prefered_color>
            </colors>
            <fur>По отношение на дължината е три типа:
                Късокосместо немско овчарско куче,
                Дългоравнокосместо немско овчарско куче,
                Дългокосместо немско овчарско куче
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!299</image>
            <size>
                <males_size>62,5 см измерено при холката ( +/- 2.5 см)</males_size>
                <females_size>57,5 см измерено при холката ( +/- 2.5 см)</females_size>
            </size>
            <weight>
                <males_weight>30-45 кг</males_weight>
                <females_weight>22-32 кг</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN297" group="GR1" section="S1.1">
            <name>Бордър Коли</name>
            <country country_code="GBR"  capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
                <country_name>Великобритания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Монархия</country_government_type>
            </country>
            <year_of_establishment>1987</year_of_establishment>
            <head>
                Череп: Сравнително широк, без изразен тил.
                Стоп: Много отчетлив.
            </head>
            <teeth> Зъбите и челюстите са здрави с перфектна, симетрична и пълна ножична захапка, т.е. 
                горните резци плътно припокриват долните и са поставени перпендикулчрно на челюстите.
            </teeth>
            <ears>
                Среден размер и текстура, поставени доста в страни. 
                Носят се изправени или полуизправени и са чувствителни при използване.
            </ears>
            <eyes>
                Разположени широко встрани, с овална форма, умерено големи, кафеви на цвят, с изключение на мраморно оцветените кучета, при които едното или и двете, или части от едното или от двете очи, могат да са сини. 
                Изражението е благородно, пронизително, будно и интелигентно.
            </eyes>
            <tail>
                Умерено дълга, коста стига най-малко до скакателните стави, поставена ниско, добре окосмена и с извивка нагоре в края, завършваща елегантния контур и баланс на кучето.
                Опашката може да се повдигне при вълнение, но никога не се носи над линията на гърба.
                
            </tail>
            <colors>
                <primary_color>Черна с бяло</primary_color>
                <secondary_color>Изцяло черно</secondary_color>
                <prefered_color> Бялото не трябва да преобладава</prefered_color>
            </colors>
            <fur>Два варианта: Умерено дълъг или гладък.
                И при двата варианта, покривния косъм е гъст и с умерена текстура, подкосъма е мек и гъст с добра водоустойчивост. 
                При умерено дългокосместия вариант, обилна козина формира грива, "бричове" и "четка". По лицето, ушите, предните крайници (изключвайки украсяващия косъм), 
                задните крайници от скакателните стави до лапите, косъмът трябва да е къс и гладък.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!307</image>
            <size>
                <males_size>53,5 см измерено при холката ( +/- 2.5 см)</males_size>
                <females_size>51,5 см измерено при холката ( +/- 2.5 см)</females_size>
            </size>
            <weight>
                <males_weight>27-30 кг</males_weight>
                <females_weight>24-27 кг</females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S1.1">Овчарски и пастирски кучета</section>
    </sections>
    <groups>
        <group group_code="GR1">ОВЧАРСКИ И ПАСТИРСКИ КУЧЕТА. КУЧЕТА ПОДКАРВАЧИ</group>
    </groups>
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_eighteenth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN97" group="GR5" section="S5.2">
            <name>Померан</name>
            <country  country_code="GBR" capital="London" official_language="British English" time_zone = "No UTC/GMT offset"  currency="Pound">
                <country_name>Великобритания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Монархия</country_government_type>
            </country>
            <year_of_establishment>1998</year_of_establishment>
            <head>
                Средноголяма, гледана отгоре изглежда най-широка в задната част и се стеснява в посока към върха на носа.
                Стоп: Средноизразен до дълбок, но никога рязък
            </head>
            <teeth>
                Челюстите са нормално развити и с пълна ножична захапка с 42 налични зъба, съответствено на зъбната формула на кучето,
                т.е. горните зъби плътно припокриват долните и са поставени в равна редица в челюстта. 
                При миниатюрния и той (померанския) шпиц липсата на няколко премолара се позволява. 
                Клещовидна захапка е позволена при всички разновидности на шпица.
            </teeth>
            <ears>
                Малките уши са поставени високо и относително близо едно до друго, триъгълни и заострени. Винаги са носени изправени, връхчетата не се клатят.
            </ears>
            <eyes>
                Очите са средни по големина, издължени, леко наклонени и тъмни. Ръбът на клепачите е черен при всички цветови разновидности, тъмнокафяв при кафявите кучета.
            </eyes>
            <tail>
                Опашката е поставена високо и е средно дълга. 
                Издига се нагоре и се завива над гърба, направо от основата. 
                Лежи плътно върху гърба и е покрита с много пухкава козина. 
                Допуска се да е двойно навита при връхчето.
            </tail>
            <colors>
                <primary_color>Черно, кафяво, бяло</primary_color>
                <secondary_color> Оранжево, зонарно сиво</secondary_color>
                <prefered_color>Няма предпочитания в окраската</prefered_color>
            </colors>
            <fur>
                Немският шпиц има двойна козина дълъг, прав и стърчащ покривен косъм и къс, гъст и подобен на памук и вълна едновременно подкосъм. 
                Главата, ушите, предната страна на крайниците и лапите са покрити с къс и гъст копринен косъм. Останалата част от тялото е с дълго, богато окосмяване. 
                Козината не е вълниста, къдрава или на шнурове, не се разделя на път на гърба. Вратът и раменете са покрити с гъста грива. 
                От задната страна на бедрата има буйно окосмяване, от крупата до скакателните стави. Опашката е пухкава.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!327</image>
            <size>
                <males_size>20 см. +/- 2 см.</males_size>
                <females_size>20 см. +/- 2 см.</females_size>
            </size>
            <weight>
                <males_weight>Трябва да има тегло, съответстващо на ръста.</males_weight>
                <females_weight>Трябва да има тегло, съответстващо на ръста.</females_weight>
            </weight>
        </dog_breed>
        
        <dog_breed standart_number="SN306" group="GR5" section="S5.4">
            <name>Западносибирска лайка</name>
            <country country_code="RUS"  capital="Moscow" official_language="Russian"  time_zone = "UTC/GMT +4 hours"  currency="Russian Ruble">
                <country_name>Русия</country_name>
                <country_continent>Евро-Азия</country_continent>
                <country_government_type>Федерация</country_government_type>
            </country>
            <year_of_establishment>1996</year_of_establishment>
            <head>
                Не голяма.
                Черепна област:
                Череп: Подобен по форма на равностранен триъгълник.
                Стоп: Прехода от черепа към муцуната е постепенен, едва забележим.
            </head>
            <teeth>
                Бели, големи; ножична захапка.
            </teeth>
            <ears>
                Изправени, поставени високо, заострени.
            </ears>
            <eyes>
                Овални, полегати, тъмни на цвят.
            </eyes>
            <tail>
                Силно навита; носи се над гърба или бедрото.
            </tail>
            <colors>
                <primary_color> Бял, сол-пипер</primary_color>
                <secondary_color> червен и сив във всички нюанси</secondary_color>
                <prefered_color>черният цвят е приемлив, както и двуцветни и на петна от изброените цветове.</prefered_color>
            </colors>
            <fur>
                Твърд защитен косъм, добре развид подкосъм. Покриващата козина е права и груба.
                Благодарение на добре развитият подкосъм, тя е до известна степен "щръкнала" и изглежда буйна. По главата, ушите и предната част на крайниците, козината е къса; по холката, 
                шията, раменете и задната част на крайниците, косъмът е по-дълъг; той формира бакенбарди по скулите, яка по шията и украса от прави косми по задните крайници.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!328</image>
            <size>
                <males_size>от 54 до 60 см.</males_size>
                <females_size>от 52 до 58 см.</females_size>
            </size>
            <weight>
                <males_weight>35-40 кг.</males_weight>
                <females_weight>32-38 кг.</females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S5.4">Европейски шпицове</section>
        <section section_id="S5.2">Северни ловни породи</section>
    </sections>
    <groups>
        <group group_code="GR5">ШПИЦОВЕ И ДРУГИ ПРИМИТИВНИ ПОРОДИ</group>
    </groups>
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_fifteenth_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        
        <dog_breed standart_number="SN61" group="GR2" section="S2.2">
            <name>Санбернар</name>
            <country country_code="SWZ"  capital="Bern" official_language="German/French" time_zone = "UTC/GMT +1 hour"  currency="Swiss franc">
                <country_name>Швейцария</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Демократична федерална република</country_government_type>
            </country>
            <year_of_establishment>1985</year_of_establishment>
            <head>
                Главата е голяма с леко квадратна форма и характерни бръчки по челото.
      
            </head>
            <teeth>
                Имат много силни зъби. Захапката може да бъде клещовидна или ножична.
                Допуска се презахапка и липса на премолар 1
                
            </teeth>
            <ears>
                Ушите са с триъгълна форма и леко повдигнат заден край. Предният ушен край прилепва към бузите
                
            </ears>
            <eyes>
                Очите са средно големи и дълбоко поставени.
            </eyes>
            <tail>
                Опашката е дълга, покрита обилно с козина. Когато кучето е в покой, тя виси отпусната надолу или е с леко извит край нагоре. Когато кучето е възбудено тя се извива нагоре.
                
                
            </tail>
            <colors>
                <primary_color>Кафеви петна на бял фон</primary_color>
                <secondary_color>Черно-кафеви петна на бял фон</secondary_color>
                <prefered_color> И двете разновидности са енакво ценени</prefered_color>
            </colors>
            <fur>
                Санбернарът се отличава с гъста, обилна и водоустойчива козина по цялото тяло. В зависимост от дължината й се различават 
                2 типа космена покривка при породата:дългокосмести и късокосмести
                               
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!317</image>
            <size>
                <males_size>70-90 см</males_size>
                <females_size> 65-80 см</females_size>
            </size>
            <weight>
                <males_weight>над 35 кг</males_weight>
                <females_weight>над 30 кг</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN101" group="GR9" section="S9.1">
            <name>Френски булдог</name>
            <country country_code="FRA"  capital="Paris" official_language="French" time_zone = "UTC/GMT +1 hour"  currency="Euro">
                <country_name>Франция</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Република</country_government_type>
            </country>
            <year_of_establishment>1994</year_of_establishment>
            <head>
                Главата е къса, спрямо дължината на черепа. Имат сплескана муцуна - брахицефална порода.
               
            </head>
            <teeth>
                Имат много силни зъби. Захапката е обратна.
               
                
            </teeth>
            <ears>
                Ушите им са тип "прилепски". По - ранните развъдчици са предпочитали клепнали розови уши, но сега всички
                Френски булдози трябва да са с "прилепски уши". В основата са по - широки, а към върха се стесняват.
                
            </ears>
            <eyes>
                Имат големи очи с овална форма, значително раздалечени едно от друго.
               
            </eyes>
            <tail>
                Опашката може да бъде права или навита. Сравнително къса е, като в основата е по - дебела.
                                
            </tail>
            <colors>
                <primary_color>Кафеви на ивици или светло оранжеви</primary_color>
                <secondary_color>Бяла или черна</secondary_color>
                <prefered_color> И двете разновидности са енакво ценени може и спесица от тях</prefered_color>
            </colors>
            <fur>
                Френският булдог имат много къса, гладка, мека и права козина, което улеснява и нейната поддръжка.
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!318</image>
            <size>
                <males_size>25-30 см</males_size>
                <females_size> 25-30 см</females_size>
            </size>
            <weight>
                <males_weight>8-10 кг</males_weight>
                <females_weight>7-9 кг</females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        
        <section section_id="S2.2">Догообразни</section>
        <section section_id="S9.1">Бишони и подобни породи</section>
    </sections>
    <groups>
        <group group_code="GR2">ПИНЧЕРИ И ШНАУЦЕРИ. ДОГООБРАЗНИ И ШВЕЙЦАРСКИ ПАСТИРСКИ КУЧЕТА</group>
        <group group_code="GR9">КУЧЕТА ЗА КОМПАНИЯ И ДЕКОРАТИВНИ (ТОЙ)</group>
    </groups>
    
</fci>

=== yoanaB/ASP/XML_Files/XML_Files/ASP_eleventh_xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fci SYSTEM "ASP_DTD.dtd">
<fci>
    <dog_breeds>
        <dog_breed standart_number="SN144" group="GR2" section="S2.2">
            <name>Боксер</name>
            <country country_code="GER"  capital="Berlin" official_language="German" time_zone = "UTC/GMT +1 hour"  currency="Euro">
                <country_name>Гемрания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Демокративна и федерална република</country_government_type>
            </country>
            <year_of_establishment>1988</year_of_establishment>
            <head>
                Главата е добре развита и мощна с издадена напред долна челюст (прогения) и притъпена муцуна.
            </head>
            <teeth>  
                Челюстите са със здрави и бели зъби, правилно разположени, добре вкоренени в развитите челюсти. Захапката е ножицообразна – резците на горната челюст леко покриват резците на долната челюст, като при това се допират един до друг. Допуска се клещовидна захапка. Пастирите са предпочитали именно такава захапка. 
                Изисква се пълна зъбна формула, допуска се отсъствие на двата първи премоляра (2 х Р1), трети молари (М3) не се вземат в предвид.
            </teeth>
            <ears>
                Ушите са високо поставени и придават буден и прям вид на Боксера.
            </ears>
            <eyes>
                Имат средно големи очи, които не са дълбоко поставени и не са много изпъкнали.
            </eyes>
            <tail>
                Опашката е високо поставена, насочена нагоре. Често се срещат боксери без 
                опашки и е много забавно да се види как въртят цялата си задница.
                
            </tail>
            <colors>
                <primary_color>Жълто - кафяв и жълто - червеникав</primary_color>
                <secondary_color>Тигров или бял</secondary_color>
                <prefered_color> И двете разновидности са приемливи</prefered_color>
            </colors>
            <fur> 
                Имат гладка и лъскава космена покривка.
                Космите са къси и прилягат плътно към тялото.
                
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!308</image>
            <size>
                <males_size>57 - 64 см </males_size>
                <females_size> 53 - 60 см</females_size>
            </size>
            <weight>
                <males_weight>25 - 30 кг</males_weight>
                <females_weight>25 - 30 кг</females_weight>
            </weight>
        </dog_breed>
        <dog_breed standart_number="SN147" group="GR2" section="S2.2">
            <name>Ротвайлер</name>
            <country country_code="GER"  capital="Berlin" official_language="German" time_zone = "UTC/GMT +1 hour"  currency="Euro">
                <country_name>Гемрания</country_name>
                <country_continent>Европа</country_continent>
                <country_government_type>Демокративна и федерална република</country_government_type>
            </country>
            <year_of_establishment>1986</year_of_establishment>
            <head>
                Имат добре замускулено тяло и средно голяма глава. Шията и крайниците са много здрави и добре замускулени. 
                Кожата е доста дебела и еластична.
            </head>
            <teeth>  
                Челюстите са със здрави и бели зъби, правилно разположени, добре вкоренени в развитите челюсти. Захапката е ножицообразна – резците на горната челюст леко покриват резците на долната челюст, като при това се допират един до друг. Допуска се клещовидна захапка. Пастирите са предпочитали именно такава захапка. 
                Изисква се пълна зъбна формула, допуска се отсъствие на двата първи премоляра (2 х Р1), трети молари (М3) не се вземат в предвид.
            </teeth>
            <ears>
                Ушите им не са много големи. Поставени са високо и висят.
            </ears>
            <eyes>
                Очите са средно големи, с бадемовидна форма.
            </eyes>
            <tail>
                Опашката е права в спокойно състояние.
                Поставена е нито много ниско, нито много високо.
                
                
            </tail>
            <colors>
                <primary_color>Черен с жълти петна</primary_color>
                <secondary_color>Черен с вълти петна</secondary_color>
                <prefered_color> Черен с жълти петна</prefered_color>
            </colors>
            <fur> 
                Ротвайлерът има гъста, дебела и средно дълга (до къса) космена покривка. 
                Космите са твърди и груби и прилягат плътно по тялото. 
                Има развит подкосъм, който не трябва да прозира през покривните косми.
                Ако кучето се отглежда при по – ниски температури се развива по – плътно подкосмие, което предпазва от студ и влага. На задните крайници космената покривка е малко по – дълга.
            </fur>
            <image>https://skydrive.live.com/redir?resid=6F26B1E0D6CF648E!290</image>
            <size>
                <males_size>61 - 68 см  </males_size>
                <females_size> 56 - 63 см</females_size>
            </size>
            <weight>
                <males_weight>35 - 50 кг  </males_weight>
                <females_weight>30 - 45 кг  </females_weight>
            </weight>
        </dog_breed>
    </dog_breeds>
    <sections>
        <section section_id="S2.2">Догообразни</section>
    </sections>
    <groups>
        <group group_code="GR2">ПИНЧЕРИ И ШНАУЦЕРИ. ДОГООБРАЗНИ И ШВЕЙЦАРСКИ ПАСТИРСКИ КУЧЕТА</group>
    </groups>
</fci>
